/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2024 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.cubrid.model;

import java.sql.SQLException;
import java.util.Arrays;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.DBDatabaseException;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.ext.cubrid.CubridConstants;
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
import org.jkiss.dbeaver.model.meta.Property;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

public class CubridTableColumn extends GenericTableColumn
{
    final static String [] customTypes = {"ENUM", "JSON"};

    public CubridTableColumn(
            @NotNull GenericTableBase table,
            @Nullable String columnName,
            @Nullable String dataType,
            @Nullable Boolean autoIncrement,
            @Nullable JDBCResultSet dbResult)
            throws DBException {
        super(table);
        if (dbResult != null) {
            setName(columnName);
            setDataType(dataType);
            setPrecision(JDBCUtils.safeGetInteger(dbResult, "prec"));
            setMaxLength(getPrecision());
            setScale(JDBCUtils.safeGetInteger(dbResult, "scale"));
            setRequired(JDBCUtils.safeGetString(dbResult, "is_nullable").equals("NO"));
            setDescription(JDBCUtils.safeGetString(dbResult, CubridConstants.COMMENT));
            setDefaultValue(JDBCUtils.safeGetString(dbResult, "default_value"));
            setAutoIncrement(autoIncrement);
            setOrdinalPosition(JDBCUtils.safeGetInteger(dbResult, "ref_order"));
            setPersisted(true);
        }
    }

    public void setDataType(@NotNull String fullTypeName) throws DBException {
        String type =  Arrays.stream(customTypes).filter(item->fullTypeName.contains(item)).findFirst().orElse(null);
        if (type == null) {
            setFullTypeName(fullTypeName);
        } else {
            setTypeName(fullTypeName);
        }
    }

    @NotNull
    @Override
    @Property(viewable = true, editable = true, updatable = true, order = 20, listProvider = ColumnTypeNameListProvider.class)
    public String getTypeName() {
        return super.getTypeName();
    }

    @Nullable
    @Override
    @Property(viewable = true, editable = true, updatable = true, order = 40)
    public long getMaxLength() {
        return super.getMaxLength();
    }

    @NotNull
    @Override
    @Property(viewable = true, editable = true, updatable = true, order = 50)
    public boolean isRequired() {
        return super.isRequired();
    }

    @Nullable
    @Override
    @Property(viewable = true, editable = true, updatable = true, order = 70)
    public String getDefaultValue() {
        return super.getDefaultValue();
    }

    @Nullable
    @Override
    public boolean isInUniqueKey() {
        return false;
    }

    @Nullable
    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Nullable
    @Override
    public int getRadix() {
        return 0;
    }

    @NotNull
    public boolean isForeignKey(@NotNull DBRProgressMonitor monitor) throws DBException {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, getDataSource(), "Load foreign key")) {
            String query = "select * from db_index a join db_index_key b on a.owner_name = b.owner_name and a.class_name = b.class_name "
                         + "and a.index_name = b.index_name where is_foreign_key = 'YES' and a.class_name = ? and b.key_attr_name = ?";
            try (JDBCPreparedStatement dbStat = session.prepareStatement(query)) {
                dbStat.setString(1, getTable().getName());
                dbStat.setString(2, getName());
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                    boolean isForeignKey = false;
                    while (dbResult.next()) {
                        isForeignKey = true;
                    }
                    return isForeignKey;
                }
            }
        } catch (SQLException e) {
            throw new DBDatabaseException(e, getDataSource());
        }
    }
}
