files:
  - source: /plugins/**/OSGI-INF/l10n/bundle.properties
    translation: /nls/bundles/**/OSGI-INF/l10n/%file_name%_%two_letters_code%.properties
  - source: /plugins/**/*Resources.properties
    translation: /nls/bundles/**/%file_name%_%two_letters_code%.properties
  - source: /plugins/**/*Messages.properties
    translation: /nls/bundles/**/%file_name%_%two_letters_code%.properties
