/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.mimer.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.DBDatabaseException;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.Log;
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
import org.jkiss.dbeaver.ext.generic.model.GenericUniqueKey;
import org.jkiss.dbeaver.ext.mimer.MimerConstants;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCStatement;
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
import org.jkiss.dbeaver.model.impl.jdbc.cache.JDBCObjectCache;
import org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn;
import org.jkiss.dbeaver.model.meta.Association;
import org.jkiss.dbeaver.model.meta.IPropertyValueListProvider;
import org.jkiss.dbeaver.model.meta.Property;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.runtime.VoidProgressMonitor;
import org.jkiss.dbeaver.model.struct.DBSEntityConstraintType;
import org.jkiss.dbeaver.model.struct.cache.DBSObjectCache;
import org.jkiss.utils.CommonUtils;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * {@code GenericTableColumn} + a {@code sequenceName} attribute backing "Auto Generated" -
 * Mimer SQL has no identity syntax, so the equivalent is a sequence + {@code DEFAULT NEXT VALUE
 * FOR "<schema>"."<seq>"} (built by {@link org.jkiss.dbeaver.ext.mimer.edit.MimerTableColumnManager}/
 * {@link org.jkiss.dbeaver.ext.mimer.edit.MimerTableManager}). {@code sequenceName} is
 * editable only while {@link #isAutoIncrement()} is checked, and is create-only - once
 * persisted, the column's own {@code DEFAULT} clause already shows it.
 *
 * @author Mimer Information Technology
 */
public class MimerTableColumn extends GenericTableColumn {

    private static final Log log = Log.getLog(MimerTableColumn.class);

    private static final Pattern SEQUENCE_DEFAULT_PATTERN = Pattern.compile(
        "(?i)(?:NEXT\\s+VALUE\\s+FOR|NEXT_VALUE\\s+OF|CURRENT_VALUE\\s+OF)\\s+\"?([^\".\\s]+)\"?\\s*\\.\\s*\"?([^\".\\s]+)\"?");

    private final MimerColumnPrivilege.PrivilegeCache privilegeCache = new MimerColumnPrivilege.PrivilegeCache();
    private final UsedByCache usedByCache = new UsedByCache();
    private List<MimerObjectUses> uses;
    private String sequenceName;
    private String collation;
    private boolean collationResolved;
    private String intervalTypeName;
    private boolean intervalTypeNameResolved;

    public MimerTableColumn(GenericTableBase table) {
        super(table);
    }

    public MimerTableColumn(
        GenericTableBase table,
        String columnName,
        String typeName,
        int valueType,
        int sourceType,
        int ordinalPosition,
        long columnSize,
        long charLength,
        Integer scale,
        Integer precision,
        int radix,
        boolean notNull,
        String remarks,
        String defaultValue,
        boolean autoIncrement,
        boolean autoGenerated
    ) {
        super(table, columnName, typeName, valueType, sourceType, ordinalPosition, columnSize,
            charLength, scale, precision, radix, notNull, remarks, defaultValue, autoIncrement, autoGenerated);
    }

    @Nullable
    @Property(viewable = true, editable = true, updatable = true,
        editableExpr = "object.autoIncrement", updatableExpr = "object.autoIncrement", order = 55)
    public String getSequenceName() {
        return sequenceName;
    }

    public void setSequenceName(String sequenceName) {
        this.sequenceName = sequenceName;
    }

    /**
     * A character-type column's collation ({@code "col" <type> COLLATE "schema"."name"}) - only
     * meaningful for a character type, see {@link #isCollationApplicable}/{@link
     * MimerConstants#isCharacterType}. Editable both at create time and afterwards - unlike
     * {@link #getSequenceName}, Mimer SQL does support changing an existing column's collation
     * (see {@link org.jkiss.dbeaver.ext.mimer.edit.MimerTableColumnManager} for the {@code ALTER
     * TABLE ... ALTER COLUMN ... SET DATA TYPE ... COLLATE ...} write side - the docs' own
     * example shows the data type has to be repeated even when only the collation changes).
     * <p>
     * For a not-yet-persisted column this is simply whatever the property grid holds - nothing
     * to read back yet. For a persisted one it's lazily resolved from {@code
     * INFORMATION_SCHEMA.COLUMNS.COLLATION_SCHEMA}/{@code COLLATION_NAME} on first read and
     * cached from then on.
     * <p>
     * Deliberately takes no {@link DBRProgressMonitor} - the property system treats any {@code
     * @Property} getter that does as "lazy" and defers it to the interactive properties tree
     * viewer's own async load job, which the generic "Create New Column" dialog ({@code
     * CustomFormEditor}, used automatically since this plugin has no column-specific create
     * dialog of its own) never triggers - it always reads properties with a {@code null} monitor,
     * so a lazy property renders blank there. Resolving with a throwaway {@link
     * VoidProgressMonitor} instead - same forced-blocking-load idiom {@link #isInUniqueKey}
     * already uses in this same class - works in the grid, the properties panel, and that create
     * dialog alike.
     * <p>
     * Gated by {@code editableExpr}/{@code updatableExpr}, not {@code visibleIf} - {@code
     * visibleIf} doesn't reliably re-evaluate per row in the Columns grid when the answer varies
     * row to row (every row came back checked-but-blank, not just non-character ones); {@code
     * editableExpr}/{@code updatableExpr} do, confirmed working per-row already ({@link
     * org.jkiss.dbeaver.ext.mimer.model.MimerDatabankFile}'s file name). See {@link
     * #isCollationApplicable} for why a not-yet-typed column counts as applicable too - the
     * generic "Create New Column" dialog filters editability exactly once, at construction,
     * before any type is picked, so a strict character-type-only check would permanently hide
     * this field there regardless of what type gets chosen afterward. That dialog can't
     * dynamically re-hide the field if a non-character type is picked mid-session either, for the
     * same reason - only the Columns grid re-evaluates live, per row, on every render.
     */
    @Nullable
    @Property(viewable = true, editableExpr = "object.collationApplicable", updatableExpr = "object.collationApplicable",
        order = 56, listProvider = CollationListProvider.class)
    public String getCollation() {
        if (isPersisted() && !collationResolved) {
            collationResolved = true;
            try {
                collation = resolveCollation(new VoidProgressMonitor());
            } catch (DBException e) {
                log.debug("Can't resolve collation for column '" + getName() + "'", e);
            }
        }
        return collation;
    }

    public void setCollation(@Nullable String collation) {
        this.collation = collation;
        this.collationResolved = true;
    }

    /**
     * Whether {@link #getCollation}/{@link #setCollation} apply to this column - see {@link
     * MimerConstants#isCharacterType}. A column with no type set yet counts as applicable too,
     * not just a genuine character type - see {@link #getCollation}'s own Javadoc for why: the
     * "Create New Column" dialog evaluates this once, before any type is picked, and a strict
     * character-type-only check would permanently hide the field there for every new column.
     */
    public boolean isCollationApplicable() {
        String typeName = getTypeName();
        return CommonUtils.isEmpty(typeName) || MimerConstants.isCharacterType(typeName);
    }

    @Nullable
    private String resolveCollation(@NotNull DBRProgressMonitor monitor) throws DBException {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, this, "Read Mimer SQL column collation")) {
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
                "SELECT COLLATION_SCHEMA, COLLATION_NAME\n" +
                "FROM INFORMATION_SCHEMA.COLUMNS\n" +
                "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?")
            ) {
                dbStat.setString(1, getTable().getSchema().getName());
                dbStat.setString(2, getTable().getName());
                dbStat.setString(3, getName());
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                    if (dbResult.next()) {
                        String schema = JDBCUtils.safeGetStringTrimmed(dbResult, "COLLATION_SCHEMA");
                        String name = JDBCUtils.safeGetStringTrimmed(dbResult, "COLLATION_NAME");
                        if (!CommonUtils.isEmpty(name)) {
                            return MimerCollation.formatReference(schema, name);
                        }
                    }
                }
            }
        } catch (SQLException e) {
            throw new DBDatabaseException(e, getDataSource());
        }
        return null;
    }

    /**
     * Every collation in the datasource (not just this table's own schema - matches how the
     * Domain/Collation create dialogs' own Collation pickers work). Stays typeable ({@link
     * #allowCustomValue()}), same reasoning as {@link MimerTable.DatabankListProvider}.
     */
    public static class CollationListProvider implements IPropertyValueListProvider<MimerTableColumn> {
        @Override
        public boolean allowCustomValue() {
            return true;
        }

        @Override
        public Object[] getPossibleValues(MimerTableColumn object) {
            if (!(object.getDataSource() instanceof MimerDataSource ds)) {
                return new Object[0];
            }
            List<Object> values = new ArrayList<>(MimerConstants.CURRENT_COLLATION_NAMES);
            try {
                for (MimerCollation c : ds.getCollations(new VoidProgressMonitor())) {
                    values.add(c.getReference());
                }
            } catch (DBException e) {
                log.debug("Can't load collation list for the column Collation property", e);
            }
            return values.toArray();
        }
    }

    /**
     * The driver's own {@code TYPE_NAME} for an {@code INTERVAL} column never carries its real
     * precision (e.g. plain {@code "INTERVAL DAY"}, or {@code "INTERVAL DAY() TO HOUR"} with
     * literal empty parens for a range): DDL built from it recreated an
     * unqualified {@code INTERVAL DAY} target column where the source was really {@code INTERVAL
     * DAY(5)}, which then overflowed on any real data needing more than the default precision.
     * <p>
     * Rebuilt here, for a persisted column, from {@code INFORMATION_SCHEMA.COLUMNS}'s own {@code
     * INTERVAL_TYPE}/{@code INTERVAL_PRECISION}/{@code DATETIME_PRECISION} - lazily resolved and
     * cached, same shape as {@link #getCollation}. Re-declares {@code @Property} matching {@link
     * org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTableColumn#getTypeName} exactly (not the
     * further ancestor {@code AbstractAttribute}'s bare version) - a property change on an
     * overridden getter only takes effect with its own annotation, and copying the wrong
     * ancestor's here first silently dropped {@code editable}/{@code listProvider}, hiding the
     * Data Type dropdown entirely for every new column, not just interval ones.
     * <p>
     * For a not-yet-persisted column, also strips any {@code "(p)"}/{@code "(p,s)"}-shaped
     * placeholder left unreplaced from picking one of {@link MimerConstants#INTERVAL_TYPE_NAMES}
     * (e.g. {@code "INTERVAL DAY(p) TO SECOND(s)"} becomes {@code "INTERVAL DAY TO SECOND"})
     * rather than sending the literal placeholder text to the server - Mimer SQL applies its own
     * default precision when none is given. A real, typed-in precision is left untouched.
     */
    @NotNull
    @Override
    @Property(viewable = true, editable = true, order = 20, listProvider = JDBCTableColumn.ColumnTypeNameListProvider.class)
    public String getTypeName() {
        String baseTypeName = super.getTypeName();
        if (!baseTypeName.toUpperCase(Locale.ENGLISH).startsWith("INTERVAL")) {
            return baseTypeName;
        }
        if (!isPersisted()) {
            return stripUnfilledIntervalPlaceholders(baseTypeName);
        }
        if (!intervalTypeNameResolved) {
            intervalTypeNameResolved = true;
            try {
                intervalTypeName = resolveIntervalTypeName(new VoidProgressMonitor());
            } catch (DBException e) {
                log.debug("Can't resolve interval precision for column '" + getName() + "'", e);
            }
        }
        return intervalTypeName != null ? intervalTypeName : baseTypeName;
    }

    private static final Pattern INTERVAL_PRECISION_GROUP = Pattern.compile("\\(([^)]*)\\)");
    private static final Pattern VALID_INTERVAL_PRECISION = Pattern.compile("\\s*\\d+\\s*(,\\s*\\d+\\s*)?");

    /**
     * Removes any parenthesized group in an {@code INTERVAL} type name whose content isn't a
     * real number (or comma-separated pair of numbers) - i.e. a leftover {@code p}/{@code s}
     * placeholder - while leaving a genuinely typed-in precision alone. Handles a range's two
     * groups (leading field, trailing {@code SECOND}) independently, so a partially-filled-in
     * type like {@code "INTERVAL DAY TO SECOND(9)"} is left with just the one real value.
     */
    static String stripUnfilledIntervalPlaceholders(@NotNull String typeName) {
        Matcher matcher = INTERVAL_PRECISION_GROUP.matcher(typeName);
        StringBuilder result = new StringBuilder();
        int lastEnd = 0;
        while (matcher.find()) {
            if (!VALID_INTERVAL_PRECISION.matcher(matcher.group(1)).matches()) {
                result.append(typeName, lastEnd, matcher.start());
                lastEnd = matcher.end();
            }
        }
        result.append(typeName.substring(lastEnd));
        return result.toString();
    }

    @Nullable
    private String resolveIntervalTypeName(@NotNull DBRProgressMonitor monitor) throws DBException {
        try (JDBCSession session = DBUtils.openMetaSession(monitor, this, "Read Mimer SQL interval column precision")) {
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
                "SELECT INTERVAL_TYPE, INTERVAL_PRECISION, DATETIME_PRECISION\n" +
                "FROM INFORMATION_SCHEMA.COLUMNS\n" +
                "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?")
            ) {
                dbStat.setString(1, getTable().getSchema().getName());
                dbStat.setString(2, getTable().getName());
                dbStat.setString(3, getName());
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                    if (dbResult.next()) {
                        String intervalType = JDBCUtils.safeGetStringTrimmed(dbResult, "INTERVAL_TYPE");
                        Integer leadingPrecision = JDBCUtils.safeGetInteger(dbResult, "INTERVAL_PRECISION");
                        Integer fractionalPrecision = JDBCUtils.safeGetInteger(dbResult, "DATETIME_PRECISION");
                        return buildIntervalTypeName(intervalType, leadingPrecision, fractionalPrecision);
                    }
                }
            }
        } catch (SQLException e) {
            throw new DBDatabaseException(e, getDataSource());
        }
        return null;
    }

    /**
     * Builds a fully-precisioned {@code INTERVAL} type declaration from {@code
     * INFORMATION_SCHEMA.COLUMNS}'s own {@code INTERVAL_TYPE} (e.g. {@code "DAY"}, {@code "DAY TO
     * HOUR"}, {@code "SECOND"}), {@code INTERVAL_PRECISION} (the leading field's precision - always
     * present, including for a lone {@code SECOND} field) and {@code DATETIME_PRECISION} (the
     * fractional-seconds precision - only meaningful when the last/only field is {@code SECOND}).
     * Matches the SQL-standard interval qualifier grammar: a lone {@code SECOND} field takes a
     * single, comma-separated {@code SECOND(leading, fractional)}; a range's trailing {@code
     * SECOND} field takes its own separate {@code SECOND(fractional)}; every other field takes a
     * plain {@code FIELD(leading)}.
     */
    @Nullable
    static String buildIntervalTypeName(@Nullable String intervalType, @Nullable Integer leadingPrecision, @Nullable Integer fractionalPrecision) {
        if (CommonUtils.isEmpty(intervalType) || leadingPrecision == null) {
            return null;
        }
        int toIndex = intervalType.toUpperCase(Locale.ENGLISH).indexOf(" TO ");
        if (toIndex == -1) {
            if ("SECOND".equalsIgnoreCase(intervalType)) {
                return "INTERVAL SECOND(" + leadingPrecision + ", " + CommonUtils.toInt(fractionalPrecision) + ")";
            }
            return "INTERVAL " + intervalType + "(" + leadingPrecision + ")";
        }
        String startField = intervalType.substring(0, toIndex);
        String endField = intervalType.substring(toIndex + " TO ".length());
        String endPart = "SECOND".equalsIgnoreCase(endField)
            ? "SECOND(" + CommonUtils.toInt(fractionalPrecision) + ")"
            : endField;
        return "INTERVAL " + startField + "(" + leadingPrecision + ") TO " + endPart;
    }

    /**
     * Column-restricted {@code INSERT}/{@code UPDATE}/{@code REFERENCES} grants - see
     * {@link MimerColumnPrivilege}.
     */
    @Association
    public Collection<MimerColumnPrivilege> getPrivileges(@NotNull DBRProgressMonitor monitor) throws DBException {
        return privilegeCache.getAllObjects(monitor, this);
    }

    @NotNull
    public DBSObjectCache<MimerTableColumn, MimerColumnPrivilege> getPrivilegeCache() {
        return privilegeCache;
    }

    /**
     * {@code GenericTableColumn.isInUniqueKey()} - what drives the "key" icon overlay in the
     * Columns tree - only ever checks whatever's already cached, never forces a load; the cache
     * only actually gets populated once something reads the table's Constraints with a real
     * monitor, normally only triggered by expanding that folder. This override forces the load
     * instead - a throwaway {@code VoidProgressMonitor} is safe since the cache is per-table and
     * only the first column checked for a given table actually queries the server.
     * <p>
     * Filters to {@code PRIMARY_KEY} constraints only, not the generic "any unique key" behavior
     * other DBeaver plugins use. {@code GenericUniqueKey} is also what {@code CHECK} constraints
     * are modeled as here (see {@link MimerMetaModel#createConstraintImpl}), and Mimer SQL's own
     * {@code KEY_COLUMN_USAGE} join can carry a column reference for those too (e.g. a named
     * {@code CHECK(col IS NOT NULL)}), so an unfiltered check would wrongly key-icon such a
     * column. A genuine {@code UNIQUE} constraint is deliberately excluded too, even though it's
     * a real key - this plugin only key-icons the primary key, not uniquely-constrained columns.
     */
    @Override
    public boolean isInUniqueKey() {
        try {
            List<GenericUniqueKey> constraints = getTable().getConstraints(new VoidProgressMonitor());
            if (constraints != null) {
                for (GenericUniqueKey key : constraints) {
                    if (key.getConstraintType() == DBSEntityConstraintType.PRIMARY_KEY && key.hasColumn(this)) {
                        return true;
                    }
                }
            }
        } catch (DBException e) {
            log.debug("Can't load constraints for '" + getTable().getName() + "' to resolve the key icon", e);
        }
        return false;
    }

    /**
     * Other database objects that reference this column - routines, views, triggers, constraints,
     * and indexes, each via its own SQL-standard {@code *_COLUMN_USAGE} view (a single query, one
     * {@code UNION} branch per referencing kind - there's no one view that covers all of them).
     */
    @Association
    public Collection<MimerObjectUsedBy> getUsedBy(@NotNull DBRProgressMonitor monitor) throws DBException {
        return usedByCache.getAllObjects(monitor, this);
    }

    /**
     * The domain and/or sequence this column depends on. The domain part is a plain catalog read;
     * the sequence part has no catalog view of its own to read - a generated column's dependency
     * on its sequence only shows up as text inside {@code COLUMN_DEFAULT} (e.g. {@code NEXT VALUE
     * FOR "s"."seq"}), so it's resolved by pattern-matching the column's own already-loaded
     * default value instead of an extra query. Recognizes both the current {@code NEXT VALUE FOR}
     * syntax (what this plugin itself generates for auto-increment columns) and the older {@code
     * NEXT_VALUE OF}/{@code CURRENT_VALUE OF} forms.
     */
    @Association
    public synchronized Collection<MimerObjectUses> getUses(@NotNull DBRProgressMonitor monitor) throws DBException {
        if (uses != null) {
            return uses;
        }
        List<MimerObjectUses> result = new ArrayList<>();
        try (JDBCSession session = DBUtils.openMetaSession(monitor, this, "Read Mimer SQL column dependencies")) {
            try (JDBCPreparedStatement dbStat = session.prepareStatement(
                "SELECT DOMAIN_SCHEMA, DOMAIN_NAME\n" +
                "FROM INFORMATION_SCHEMA.COLUMNS\n" +
                "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ? AND DOMAIN_NAME IS NOT NULL")
            ) {
                dbStat.setString(1, getTable().getSchema().getName());
                dbStat.setString(2, getTable().getName());
                dbStat.setString(3, getName());
                try (JDBCResultSet dbResult = dbStat.executeQuery()) {
                    if (dbResult.next()) {
                        result.add(new MimerObjectUses(this,
                            JDBCUtils.safeGetString(dbResult, "DOMAIN_SCHEMA"),
                            JDBCUtils.safeGetString(dbResult, "DOMAIN_NAME"),
                            "DOMAIN"));
                    }
                }
            }
        } catch (SQLException e) {
            throw new DBDatabaseException(e, getDataSource());
        }
        String defaultValue = getDefaultValue();
        if (defaultValue != null) {
            Matcher matcher = SEQUENCE_DEFAULT_PATTERN.matcher(defaultValue);
            if (matcher.find()) {
                result.add(new MimerObjectUses(this, matcher.group(1), matcher.group(2), "SEQUENCE"));
            }
        }
        uses = result;
        return uses;
    }

    static class UsedByCache extends JDBCObjectCache<MimerTableColumn, MimerObjectUsedBy> {
        @NotNull
        @Override
        protected JDBCStatement prepareObjectsStatement(@NotNull JDBCSession session, @NotNull MimerTableColumn owner) throws SQLException {
            JDBCPreparedStatement stmt = session.prepareStatement(
                "SELECT RCU.ROUTINE_SCHEMA AS USING_OBJECT_SCHEMA, RCU.ROUTINE_NAME AS USING_OBJECT_NAME, R.ROUTINE_TYPE AS USING_OBJECT_TYPE\n" +
                "FROM INFORMATION_SCHEMA.ROUTINE_COLUMN_USAGE RCU JOIN INFORMATION_SCHEMA.ROUTINES R\n" +
                "  ON RCU.SPECIFIC_SCHEMA = R.SPECIFIC_SCHEMA AND RCU.SPECIFIC_NAME = R.SPECIFIC_NAME\n" +
                "  AND RCU.ROUTINE_SCHEMA = R.ROUTINE_SCHEMA AND RCU.ROUTINE_NAME = R.ROUTINE_NAME\n" +
                "WHERE RCU.TABLE_SCHEMA = ? AND RCU.TABLE_NAME = ? AND RCU.COLUMN_NAME = ?\n" +
                "UNION\n" +
                "SELECT VIEW_SCHEMA, VIEW_NAME, 'VIEW'\n" +
                "FROM INFORMATION_SCHEMA.VIEW_COLUMN_USAGE\n" +
                "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?\n" +
                "UNION\n" +
                "SELECT TRIGGER_SCHEMA, TRIGGER_NAME, 'TRIGGER'\n" +
                "FROM INFORMATION_SCHEMA.TRIGGER_COLUMN_USAGE\n" +
                "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?\n" +
                "UNION\n" +
                "SELECT CONSTRAINT_SCHEMA, CONSTRAINT_NAME, 'CONSTRAINT'\n" +
                "FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE\n" +
                "WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?\n" +
                "UNION\n" +
                "SELECT INDEX_SCHEMA, INDEX_NAME, 'INDEX'\n" +
                "FROM INFORMATION_SCHEMA.EXT_INDEX_COLUMN_USAGE\n" +
                "WHERE INDEX_SCHEMA = ? AND TABLE_NAME = ? AND COLUMN_NAME = ?");
            String schema = owner.getTable().getSchema().getName();
            String table = owner.getTable().getName();
            String column = owner.getName();
            int paramIndex = 1;
            for (int branch = 0; branch < 5; branch++) {
                stmt.setString(paramIndex++, schema);
                stmt.setString(paramIndex++, table);
                stmt.setString(paramIndex++, column);
            }
            return stmt;
        }

        @Override
        protected MimerObjectUsedBy fetchObject(@NotNull JDBCSession session, @NotNull MimerTableColumn owner, @NotNull JDBCResultSet resultSet) throws SQLException, DBException {
            return new MimerObjectUsedBy(owner, resultSet);
        }
    }
}
