package org.jkiss.dbeaver.ext.yashandb.model;

import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
import org.jkiss.dbeaver.model.meta.Property;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.struct.DBSDataType;
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
import org.jkiss.dbeaver.model.struct.DBSTypedObjectEx;

import java.sql.ResultSet;
import java.sql.Types;

/**
 * @Author: donghy
 * @Date: 2022/08
 * @Description:
 */
public class YashanDBDataTypeAttribute extends YashanDBDataTypeMember
        implements DBSEntityAttribute, DBSTypedObjectEx {

    private final YashanDBDataType attrType;
    private final YashanDBDataTypeModifier attrTypeMod;
    private final Integer length;
    private final Integer precision;
    private final Integer scale;

    public YashanDBDataTypeAttribute(DBRProgressMonitor monitor, YashanDBDataType dataType, ResultSet dbResult) {
        super(dataType, dbResult);
        this.name = JDBCUtils.safeGetString(dbResult, "ATTR_NAME");
        this.number = JDBCUtils.safeGetInt(dbResult, "ATTR_NO");
        this.attrType = YashanDBDataType.resolveDataType(
                monitor,
                getDataSource(),
                JDBCUtils.safeGetString(dbResult, "ATTR_TYPE_OWNER"),
                JDBCUtils.safeGetString(dbResult, "ATTR_TYPE_NAME"));
        this.attrTypeMod = YashanDBDataTypeModifier.resolveTypeModifier(JDBCUtils.safeGetString(dbResult, "ATTR_TYPE_MOD"));
        this.length = JDBCUtils.safeGetInteger(dbResult, "LENGTH");
        this.precision = JDBCUtils.safeGetInteger(dbResult, "PRECISION");
        this.scale = JDBCUtils.safeGetInteger(dbResult, "SCALE");
    }

    @Property(viewable = true, editable = true, order = 3)
    public YashanDBDataType getDataType() {
        return attrType;
    }

    @Property(viewable = true, editable = true, order = 4)
    public YashanDBDataTypeModifier getAttrTypeMod() {
        return attrTypeMod;
    }

    @Override
    @Property(viewable = true, editable = true, order = 6)
    public Integer getPrecision() {
        return precision == null ? 0 : precision;
    }

    @Property(viewable = true, editable = true, order = 5)
    @Override
    public long getMaxLength() {
        return length == null ? 0 : length;
    }

    @Override
    public long getTypeModifiers() {
        return 0;
    }

    @Override
    @Property(viewable = true, editable = true, order = 7)
    public Integer getScale() {
        return scale == null ? 0 : scale;
    }

    @Override
    public int getTypeID() {
        if (attrTypeMod == YashanDBDataTypeModifier.REF) {
            return Types.REF;
        }
        return attrType.getTypeID();
    }

    @Override
    public DBPDataKind getDataKind() {
        if (attrTypeMod == YashanDBDataTypeModifier.REF) {
            return DBPDataKind.REFERENCE;
        }
        return attrType.getDataKind();
    }

    @Override
    public String getTypeName() {
        return attrType.getFullyQualifiedName(DBPEvaluationContext.DDL);
    }

    @Override
    public String getFullTypeName() {
        return DBUtils.getFullTypeName(this);
    }

    @Override
    public boolean isRequired() {
        return false;
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Property(viewable = true, order = 2)
    @Override
    public int getOrdinalPosition() {
        return number - 1;
    }

    @Override
    public String getDefaultValue() {
        return null;
    }

    @Override
    public String toString() {
        return getParentObject().getFullyQualifiedName(DBPEvaluationContext.UI) + "." + getName();
    }
}
