/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.dynamodb.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.DBPDataSource;
import org.jkiss.dbeaver.model.struct.DBSEntity;
import org.jkiss.dbeaver.model.struct.DBSEntityAttribute;
import org.jkiss.dbeaver.model.struct.DBSObject;

public class DynamoDBAttribute implements DBSEntityAttribute {

    private final DynamoDBTable table;
    private final String name;
    private final String dynamoType;
    private final int ordinalPosition;
    private final boolean keyAttribute;
    private final boolean partitionKey;

    public DynamoDBAttribute(
            @NotNull DynamoDBTable table,
            @NotNull String name,
            @NotNull String dynamoType,
            int ordinalPosition,
            boolean keyAttribute,
            boolean partitionKey) {
        this.table = table;
        this.name = name;
        this.dynamoType = dynamoType;
        this.ordinalPosition = ordinalPosition;
        this.keyAttribute = keyAttribute;
        this.partitionKey = partitionKey;
    }

    @NotNull
    @Override
    public String getName() {
        return name;
    }

    @Nullable
    @Override
    public String getDescription() {
        return keyAttribute ? (partitionKey ? "Partition Key" : "Sort Key") : null;
    }

    @Override
    public boolean isPersisted() {
        return true;
    }

    @NotNull
    @Override
    public DBSEntity getParentObject() {
        return table;
    }

    @NotNull
    @Override
    public DBPDataKind getDataKind() {
        return DynamoDBTypeMapper.getDataKind(dynamoType);
    }

    @NotNull
    @Override
    public String getTypeName() {
        return DynamoDBTypeMapper.getTypeName(dynamoType);
    }

    @NotNull
    @Override
    public String getFullTypeName() {
        return getTypeName();
    }

    @Override
    public int getTypeID() {
        return DynamoDBTypeMapper.getJdbcTypeId(dynamoType);
    }

    @Override
    public long getMaxLength() {
        return 0;
    }

    @Nullable
    @Override
    public Integer getScale() {
        return null;
    }

    @Nullable
    @Override
    public Integer getPrecision() {
        return null;
    }

    @Override
    public long getTypeModifiers() {
        return 0;
    }

    @Override
    public int getOrdinalPosition() {
        return ordinalPosition;
    }

    @Override
    public boolean isRequired() {
        return keyAttribute;
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Nullable
    @Override
    public String getDefaultValue() {
        return null;
    }

    @NotNull
    @Override
    public DBPDataSource getDataSource() {
        return table.getDataSource();
    }

    public boolean isPartitionKey() {
        return partitionKey;
    }

    public boolean isKeyAttribute() {
        return keyAttribute;
    }

    @NotNull
    public String getDynamoType() {
        return dynamoType;
    }
}
