/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.dynamodb.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.exec.DBCAttributeMetaData;
import org.jkiss.dbeaver.model.exec.DBCEntityMetaData;

public class DynamoDBResultSetColumn implements DBCAttributeMetaData {

    private final String name;
    private final String dynamoType;
    private final int ordinal;

    public DynamoDBResultSetColumn(@NotNull String name, @NotNull String dynamoType, int ordinal) {
        this.name = name;
        this.dynamoType = dynamoType;
        this.ordinal = ordinal;
    }

    @NotNull
    @Override
    public String getName() {
        return name;
    }

    @NotNull
    @Override
    public String getLabel() {
        return name;
    }

    @Override
    public int getOrdinalPosition() {
        return ordinal;
    }

    @NotNull
    @Override
    public String getTypeName() {
        return DynamoDBTypeMapper.getTypeName(dynamoType);
    }

    @NotNull
    @Override
    public String getFullTypeName() {
        return getTypeName();
    }

    @Override
    public int getTypeID() {
        return DynamoDBTypeMapper.getJdbcTypeId(dynamoType);
    }

    @NotNull
    @Override
    public DBPDataKind getDataKind() {
        return DynamoDBTypeMapper.getDataKind(dynamoType);
    }

    @Override
    public long getMaxLength() {
        return 0;
    }

    @Nullable
    @Override
    public Integer getScale() {
        return null;
    }

    @Nullable
    @Override
    public Integer getPrecision() {
        return null;
    }

    @Override
    public long getTypeModifiers() {
        return 0;
    }

    @Override
    public boolean isRequired() {
        return false;
    }

    @Override
    public boolean isAutoGenerated() {
        return false;
    }

    @Override
    public boolean isReadOnly() {
        return false;
    }

    @Nullable
    @Override
    public Object getSource() {
        return null;
    }

    @Nullable
    @Override
    public String getEntityName() {
        return null;
    }

    @Nullable
    @Override
    public DBCEntityMetaData getEntityMetaData() {
        return null;
    }
}
