/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.polardbx.mysql.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.ext.mysql.model.MySQLCatalog;
import org.jkiss.dbeaver.ext.mysql.MySQLConstants;
import org.jkiss.dbeaver.ext.mysql.model.MySQLTableBase;
import org.jkiss.dbeaver.ext.mysql.model.MySQLTableColumn;
import org.jkiss.dbeaver.model.DBPEvaluationContext;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCPreparedStatement;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * PolarDB-X table cache - minimal version.
 * Focused on solving the core problem: fixing the issue where DBeaver cannot display column information of non-system table views.
 */
public class PolarDBXTableCache extends MySQLCatalog.TableCache {

    /**
     * Determine whether this is a system table/view.
     */
    private boolean isSystemTable(@NotNull MySQLCatalog owner) {
        String schemaName = owner.getName();
        
        // System databases
        return MySQLConstants.INFO_SCHEMA_NAME.equalsIgnoreCase(schemaName) ||
               "mysql".equalsIgnoreCase(schemaName) ||
               "performance_schema".equalsIgnoreCase(schemaName) ||
               "sys".equalsIgnoreCase(schemaName);
    }

    @Override
    public synchronized void loadChildren(
        @NotNull DBRProgressMonitor monitor,
        @NotNull MySQLCatalog owner,
        @Nullable final MySQLTableBase forObject
    ) throws DBException {

        // Only apply the DESCRIBE optimization to non-system views.
        if (forObject != null && forObject.isView() && !isSystemTable(owner)) {
            loadViewColumnsViaDescribe(monitor, owner, forObject);
            return;
        }

        // Use the standard logic for other cases.
        super.loadChildren(monitor, owner, forObject);
    }

    /**
     * Load view column information using the DESCRIBE command.
     * Fixes the PolarDB-X context-dependency issue: ensures DESCRIBE is executed in the correct database context.
     */
    private void loadViewColumnsViaDescribe(
        @NotNull DBRProgressMonitor monitor,
        @NotNull MySQLCatalog owner,
        @NotNull MySQLTableBase viewObject
    ) throws DBException {

        try (JDBCSession session = DBUtils.openMetaSession(monitor, owner, "Load view columns via DESCRIBE")) {
            // Key fix: first switch to the correct database context.
            String schemaName = owner.getName();
            try (JDBCPreparedStatement useStmt = session.prepareStatement(
                "USE " + DBUtils.getQuotedIdentifier(owner.getDataSource(), schemaName))) {
                useStmt.execute();
            }

            // Use the simple table name for DESCRIBE, since we are already in the correct database context.
            final String sql = "DESCRIBE " + DBUtils.getQuotedIdentifier(owner.getDataSource(), viewObject.getName());

            try (JDBCPreparedStatement stmt = session.prepareStatement(sql);
                 JDBCResultSet rs = stmt.executeQuery()) {

                final List<MySQLTableColumn> columns = new ArrayList<>();
                int ordinalPosition = 1;

                while (rs.next()) {
                    String columnName = rs.getString("Field");
                    String typeInfo = rs.getString("Type");
                    String nullable = rs.getString("Null");
                    String defaultValue = rs.getString("Default");
                    String extra = rs.getString("Extra");

                    MySQLTableColumn col = new MySQLTableColumn(viewObject);
                    col.setName(columnName);
                    col.setOrdinalPosition(ordinalPosition++);
                    col.setRequired(!"YES".equalsIgnoreCase(nullable));
                    col.setAutoGenerated(extra != null && extra.toLowerCase().contains("auto_increment"));

                    // Use the type information returned by DESCRIBE directly, converted to lower case.
                    if (typeInfo != null) {
                        col.setFullTypeName(typeInfo.toLowerCase());
                    }

                    // Set the default value.
                    if (defaultValue != null && !"NULL".equalsIgnoreCase(defaultValue)) {
                        col.setDefaultValue(defaultValue);
                    }

                    columns.add(col);
                }

                cacheChildren(viewObject, columns);
            }
        } catch (SQLException e) {
            // Fall back to the standard logic on failure.
            super.loadChildren(monitor, owner, viewObject);
        }
    }
}
