/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.yashandb.edit;

import org.jkiss.code.NotNull;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.ext.oracle.edit.OracleTableColumnManager;
import org.jkiss.dbeaver.ext.oracle.model.OracleDataType;
import org.jkiss.dbeaver.ext.oracle.model.OracleTableBase;
import org.jkiss.dbeaver.ext.yashandb.model.YashanDBTableColumn;
import org.jkiss.dbeaver.model.DBPDataKind;
import org.jkiss.dbeaver.model.edit.DBECommandContext;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.struct.DBSDataType;

import java.util.Map;


/**
 * YashanDBTableColumnManager
 */
public class YashanDBTableColumnManager extends OracleTableColumnManager {

    @Override
    protected YashanDBTableColumn createDatabaseObject(@NotNull DBRProgressMonitor monitor,
                                                       @NotNull DBECommandContext context, Object container, Object copyFrom,
                                                       @NotNull Map<String, Object> options) throws DBException {
        OracleTableBase table = (OracleTableBase) container;

        final YashanDBTableColumn column = new YashanDBTableColumn(table);

        if (copyFrom instanceof YashanDBTableColumn yashadbTabelColumn) {

            column.setName(yashadbTabelColumn.getName());
            if (yashadbTabelColumn.getDataType() != null) {
                column.setDataType(yashadbTabelColumn.getDataType());
            }
            column.setTypeName(yashadbTabelColumn.getTypeName());
            column.setMaxLength(yashadbTabelColumn.getMaxLength());
            column.setPrecision(yashadbTabelColumn.getPrecision());
            column.setScale(yashadbTabelColumn.getScale());
            column.setValueType(yashadbTabelColumn.getTypeID());
            column.setRequired(yashadbTabelColumn.isRequired());
            column.setAutoGenerated(yashadbTabelColumn.isAutoGenerated());
            column.setDefaultValue(yashadbTabelColumn.getDefaultValue());

        } else {
            DBSDataType columnType = findBestDataType(table, "VARCHAR");

            column.setName(getNewColumnName(monitor, context, table));
            if (columnType != null) {
                column.setDataType((OracleDataType) columnType);
                column.setTypeName(columnType.getName());
                column.setMaxLength(columnType.getDataKind() == DBPDataKind.STRING ? 100 : 0);
                column.setValueType(columnType.getTypeID());
            }
        }

        column.setOrdinalPosition(-1);
        return column;
    }
}
