<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.jkiss.dbeaver</groupId>
        <artifactId>plugins</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../</relativePath>
    </parent>
    <artifactId>org.jkiss.dbeaver.ext.iotdb.ui</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>eclipse-plugin</packaging>
<!--    <dependencies>-->
<!--        <dependency>-->
<!--            <groupId>org.jkiss.dbeaver</groupId>-->
<!--            <artifactId>org.jkiss.dbeaver.ext.iotdb</artifactId>-->
<!--            <version>1.0.0-SNAPSHOT</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jkiss.dbeaver</groupId>-->
<!--            <artifactId>org.jkiss.dbeaver.ui.editors.base</artifactId>-->
<!--            <version>1.0.151-SNAPSHOT</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jkiss.dbeaver</groupId>-->
<!--            <artifactId>org.jkiss.dbeaver.ui</artifactId>-->
<!--            <version>5.1.166-SNAPSHOT</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.swt.cocoa.macosx.x86_64 &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.platform</groupId>-->
<!--            <artifactId>org.eclipse.swt.cocoa.macosx.x86_64</artifactId>-->
<!--            <version>3.128.0</version>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.jface &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.platform</groupId>-->
<!--            <artifactId>org.eclipse.jface</artifactId>-->
<!--            <version>3.35.100</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jkiss.dbeaver</groupId>-->
<!--            <artifactId>org.jkiss.dbeaver.model</artifactId>-->
<!--            <version>2.0.11-SNAPSHOT</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jetbrains</groupId>-->
<!--            <artifactId>annotations</artifactId>-->
<!--            <version>13.0</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jkiss.dbeaver</groupId>-->
<!--            <artifactId>org.jkiss.dbeaver.ui.navigator</artifactId>-->
<!--            <version>1.0.151-SNAPSHOT</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jkiss.dbeaver</groupId>-->
<!--            <artifactId>org.jkiss.dbeaver.ui.editors.connection</artifactId>-->
<!--            <version>1.0.142-SNAPSHOT</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jkiss.dbeaver</groupId>-->
<!--            <artifactId>org.jkiss.dbeaver.ext.generic.ui</artifactId>-->
<!--            <version>1.0.127-SNAPSHOT</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jkiss.dbeaver</groupId>-->
<!--            <artifactId>org.jkiss.dbeaver.registry</artifactId>-->
<!--            <version>1.0.145-SNAPSHOT</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->

<!--    </dependencies>-->
</project>
