/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.frostlake.model;

import org.jkiss.dbeaver.ext.generic.model.GenericSQLDialect;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCDatabaseMetaData;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCSession;
import org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource;

import java.util.Arrays;

/**
 * Frostlake's SQL dialect. Frostlake implements Snowflake's SQL, so the dialect follows Snowflake:
 * double-quoted identifiers that preserve case, unquoted ones folded to upper case, and $$-quoted
 * routine bodies.
 *
 * <p>The three vocabularies below are GENERATED from the engine itself, not hand-picked: the
 * keywords are every keyword token in the engine's ANTLR grammar, the functions are what
 * {@code SHOW BUILTIN FUNCTIONS} enumerates (the same registry the engine dispatches through), and
 * the types are the grammar's type names. They are kept disjoint — a name is a type, or a function,
 * or a keyword — so each is categorised once and colours consistently in the editor.
 *
 * <p>Regenerate after grammar or FunctionRegistry changes; a name missing here only costs
 * highlighting and completion, never correctness.
 */
public class FrostlakeSQLDialect extends GenericSQLDialect {

    /** Every keyword token in the engine grammar that is not a type or function name (395). */
    private static final String[] FROSTLAKE_KEYWORDS = {
        "ACCESS", "ACCOUNT", "ACCOUNTS", "ACTION", "ADD", "AFTER", "ALL", "ALLOWED_VALUES",
        "ALLOW_OVERLAPPING_EXECUTION", "ALTER", "ANY", "APPEND_ONLY", "APPLICATION", "APPLY", "AS",
        "ASC", "ASOF", "ASYNC", "AT", "ATTRIBUTES", "AUTO", "AUTOINCREMENT", "AUTO_INGEST",
        "AUTO_RESUME", "AUTO_SUSPEND", "AUTO_SUSPEND_SECS", "AWAIT", "AWS_SNS_TOPIC",
        "BACKUP_INSTANCE_FAMILIES", "BEFORE", "BEGIN", "BERNOULLI", "BREAK", "BUILTIN", "BY", "CALL",
        "CALLED", "CALLER", "CASCADE", "CHANGES", "CLASS", "CLONE", "CLOSE", "CLUSTER", "COLLATE",
        "COLUMN", "COLUMNS", "COMMENT", "COMMIT", "COMPRESSION", "COMPUTE", "CONNECT",
        "CONNECT_BY_ROOT", "CONSTRAINT", "CONTINUE", "COPY", "CORTEX", "CREATE", "CROSS", "CUBE",
        "CURRENT", "CURRVAL", "CURSOR", "DATA", "DATABASE", "DATABASES", "DATA_RETENTION_TIME_IN_DAYS",
        "DATE_FORMAT", "DAYS", "DECLARE", "DEFAULT", "DEFAULT_NAMESPACE", "DEFAULT_ROLE",
        "DEFAULT_SECONDARY_ROLES", "DEFAULT_WAREHOUSE", "DELETE", "DELIMITER", "DESC", "DESCRIBE",
        "DIRECTED", "DIRECTORY", "DISABLE", "DISABLED", "DISPLAY_NAME", "DISTINCT", "DO", "DOWNSTREAM",
        "DROP", "DYNAMIC", "ECONOMY", "ELSE", "ELSEIF", "EMAIL", "EMBEDDING_MODEL", "ENABLE",
        "ENABLE_QUERY_ACCELERATION", "ENCRYPTION", "END", "ERROR_INTEGRATION", "ESCAPE", "EXCEPT",
        "EXCEPTION", "EXCLUDE", "EXECUTE", "EXECUTION", "EXISTS", "EXPLAIN", "FALSE", "FAMILIES",
        "FETCH", "FIELDS", "FIELD_DELIMITER", "FILES", "FILE_FORMAT", "FIRST", "FIRST_NAME",
        "FOLLOWING", "FOR", "FORCE", "FOREIGN", "FORMAT", "FORMATS", "FROM", "FULL", "FUNCTION",
        "FUNCTIONS", "FUTURE", "GENERATION", "GLOBAL", "GRANT", "GRANTS", "GROUP", "HANDLER", "HAVING",
        "HEADER", "HISTORY", "HOURS", "HYBRID", "ICEBERG", "IDENTIFIER", "IDENTITY", "IF", "IGNORE",
        "IMMEDIATE", "IMMUTABLE", "IMPORT", "IMPORTED", "IMPORTS", "INCLUDE", "INCREMENT",
        "INCREMENTAL", "INFORMATION", "INITIALIZE", "INITIALLY_SUSPENDED", "INNER", "INPUT", "INSTANCE",
        "INSTANCE_FAMILY", "INTEGRATION", "INTERSECT", "INTERVAL", "INTO", "IS", "JAVA", "JAVASCRIPT",
        "JOIN", "KEY", "KEYS", "LANGUAGE", "LAST", "LAST_NAME", "LATERAL", "LET", "LIMIT", "LIST",
        "LOCAL", "LOCKS", "LOGIN_NAME", "LOOP", "MANAGE", "MASKING", "MASKING_POLICY", "MATCHED",
        "MATCH_BY_COLUMN_NAME", "MATCH_CONDITION", "MATERIALIZED", "MAX_CLUSTER_COUNT",
        "MAX_CONCURRENCY_LEVEL", "MAX_FILE_SIZE", "MAX_NODES", "MERGE", "MIDDLE_NAME", "MINUS",
        "MINUTES", "MIN_CLUSTER_COUNT", "MIN_NODES", "MODIFY", "MONITOR", "MONTHS",
        "MULTI_STATEMENT_COUNT", "MUST_CHANGE_PASSWORD", "NATURAL", "NETWORK", "NEXT", "NEXTVAL", "NO",
        "NOORDER", "NORELY", "NULL", "NULLS", "OBJECTS", "OF", "OFFSET", "ON", "ONLY", "ON_CREATE",
        "ON_ERROR", "ON_SCHEDULE", "OPEN", "OPERATE", "ORDER", "ORGANIZATION", "OTHER", "OUTER", "OVER",
        "OVERWRITE", "OWNER", "OWNERSHIP", "PACKAGE", "PACKAGES", "PARAMETERS", "PARTITION", "PASSWORD",
        "PATH", "PATTERN", "PAUSE", "PIPE", "PIPES", "PIVOT", "PLACEMENT_GROUP", "POLICIES", "POLICY",
        "POOL", "POOLS", "PRECEDING", "PRECISION", "PRIMARY", "PRIOR", "PRIVILEGES", "PROCEDURE",
        "PROCEDURES", "PURGE", "PUT", "PYTHON", "QUALIFY", "QUERY_ACCELERATION_MAX_SCALE_FACTOR",
        "RAISE", "RANGE", "READ", "READ_ONLY", "REBUILD", "RECORD_DELIMITER", "RECURSIVE", "REFERENCES",
        "REFRESH", "REFRESH_MODE", "RELY", "REMOVE", "RENAME", "REPEATABLE", "RESOURCE",
        "RESOURCE_MONITOR", "RESPECT", "RESTART", "RESTRICT", "RESULT", "RESULTSET", "RESUME", "RETURN",
        "RETURNS", "REVOKE", "RM", "ROLE", "ROLES", "ROLLBACK", "ROLLUP", "ROW", "ROWCOUNT", "ROWS",
        "ROW_ACCESS_POLICY", "RUNTIME_VERSION", "SAMPLE", "SCALA", "SCALING_POLICY", "SCHEDULE",
        "SCHEMA", "SCHEMAS", "SECONDARY", "SECONDS", "SECURE", "SEED", "SELECT", "SEQUENCE",
        "SEQUENCES", "SERVERLESS_TASK_MAX_STATEMENT_SIZE", "SERVICE", "SERVICES", "SESSION", "SESSIONS",
        "SESSION_POLICY", "SET", "SETS", "SHARE", "SHOW", "SHOW_INITIAL_ROWS", "SINGLE", "SIZE_LIMIT",
        "SKIP_HEADER", "SOME", "SQL", "STAGE", "STAGES", "STANDARD", "START", "STARTS", "STATEMENT",
        "STATEMENT_QUEUED_TIMEOUT_IN_SECONDS", "STATEMENT_TIMEOUT_IN_SECONDS", "STOP", "STREAM",
        "STREAMS", "STRICT", "SUSPEND", "SUSPEND_TASK_AFTER_NUM_FAILURES", "SWAP", "SYSTEM", "TABLE",
        "TABLES", "TABLESAMPLE", "TAG", "TAGS", "TARGET_COMPLETION_INTERVAL", "TARGET_LAG", "TASK",
        "TASKS", "TASK_AUTO_RETRY_ATTEMPTS", "TEMP", "TEMPORARY", "TERSE", "THEN", "TIMELIMIT", "TO",
        "TOP", "TRANSACTION", "TRANSACTIONS", "TRANSIENT", "TRUE", "TYPE", "UNBOUNDED", "UNDROP",
        "UNION", "UNIQUE", "UNPIVOT", "UNSET", "UNTIL", "UPDATE", "URL", "USAGE", "USE", "USER",
        "USERS", "USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE",
        "USER_TASK_MINIMUM_TRIGGER_INTERVAL_IN_SECONDS", "USER_TASK_TIMEOUT_MS", "USE_ANY_ROLE",
        "USING", "VALIDATION_MODE", "VALUES", "VARIABLES", "VARYING", "VIEW", "VIEWS", "VOLATILE",
        "WAREHOUSE", "WAREHOUSES", "WAREHOUSE_SIZE", "WAREHOUSE_TYPE", "WHEN", "WHERE", "WHILE", "WITH",
        "WITHIN", "WRITE", "YEARS", "ZONE"
    };

    /** Every built-in the engine dispatches, as SHOW BUILTIN FUNCTIONS enumerates them (553). */
    private static final String[] FROSTLAKE_FUNCTIONS = {
        "ABS", "ACOS", "ACOSH", "ADD_MONTHS", "AI_AGG", "AI_CLASSIFY", "AI_COMPLETE", "AI_COUNT_TOKENS",
        "AI_FILTER", "AI_SENTIMENT", "AI_SIMILARITY", "AI_SUMMARIZE", "AI_SUMMARIZE_AGG",
        "AI_TRANSLATE", "AND", "ANY_VALUE", "APPROXIMATE_COUNT_DISTINCT", "APPROX_COUNT_DISTINCT",
        "APPROX_PERCENTILE", "ARRAYAGG", "ARRAYS_OVERLAP", "ARRAYS_TO_OBJECT", "ARRAYS_ZIP",
        "ARRAY_AGG", "ARRAY_APPEND", "ARRAY_CAT", "ARRAY_COMPACT", "ARRAY_CONSTRUCT",
        "ARRAY_CONSTRUCT_COMPACT", "ARRAY_CONTAINS", "ARRAY_DISTINCT", "ARRAY_EXCEPT", "ARRAY_FLATTEN",
        "ARRAY_GENERATE_RANGE", "ARRAY_INSERT", "ARRAY_INTERSECTION", "ARRAY_MAX", "ARRAY_MIN",
        "ARRAY_POSITION", "ARRAY_PREPEND", "ARRAY_REMOVE", "ARRAY_REMOVE_AT", "ARRAY_REPEAT",
        "ARRAY_REVERSE", "ARRAY_SIZE", "ARRAY_SLICE", "ARRAY_SORT", "ARRAY_TO_STRING",
        "ARRAY_UNION_AGG", "ARRAY_UNIQUE_AGG", "ASCII", "ASIN", "ASINH", "AS_ARRAY", "AS_BINARY",
        "AS_BOOLEAN", "AS_CHAR", "AS_DATE", "AS_DECIMAL", "AS_DOUBLE", "AS_INTEGER", "AS_NUMBER",
        "AS_OBJECT", "AS_REAL", "AS_TIME", "AS_TIMESTAMP_LTZ", "AS_TIMESTAMP_NTZ", "AS_TIMESTAMP_TZ",
        "AS_VARCHAR", "ATAN", "ATAN2", "ATANH", "AVG", "BASE64_DECODE_BINARY", "BASE64_DECODE_STRING",
        "BASE64_ENCODE", "BETWEEN", "BINARY_AS_STRING", "BITAND", "BITANDAGG", "BITAND_AGG", "BITCOUNT",
        "BITNOT", "BITOR", "BITORAGG", "BITOR_AGG", "BITSHIFTLEFT", "BITSHIFTRIGHT", "BITXOR",
        "BITXORAGG", "BITXOR_AGG", "BIT_AND", "BIT_ANDAGG", "BIT_AND_AGG", "BIT_LENGTH", "BIT_NOT",
        "BIT_OR", "BIT_ORAGG", "BIT_OR_AGG", "BIT_SHIFTLEFT", "BIT_SHIFTRIGHT", "BIT_XOR", "BIT_XORAGG",
        "BIT_XOR_AGG", "BOOLAND", "BOOLAND_AGG", "BOOLNOT", "BOOLOR", "BOOLOR_AGG", "BOOLXOR",
        "BOOLXOR_AGG", "CASE", "CAST", "CBRT", "CEIL", "CHARINDEX", "CHAR_LENGTH", "CHECK_JSON",
        "CHECK_XML", "CHR", "COALESCE", "COMPRESS", "CONCAT", "CONCAT_WS", "CONDITIONAL_CHANGE_EVENT",
        "CONDITIONAL_TRUE_EVENT", "CONTAINS", "CONVERT_TIMEZONE", "CORR", "COS", "COSH", "COT", "COUNT",
        "COUNT_IF", "COVAR_POP", "COVAR_SAMP", "CUME_DIST", "CURRENT_ACCOUNT", "CURRENT_ACCOUNT_NAME",
        "CURRENT_AVAILABLE_ROLES", "CURRENT_CLIENT", "CURRENT_DATABASE", "CURRENT_DATE",
        "CURRENT_IP_ADDRESS", "CURRENT_ORGANIZATION_NAME", "CURRENT_REGION", "CURRENT_ROLE",
        "CURRENT_ROLE_TYPE", "CURRENT_SCHEMA", "CURRENT_SCHEMAS", "CURRENT_SECONDARY_ROLES",
        "CURRENT_SESSION", "CURRENT_STATEMENT", "CURRENT_TIME", "CURRENT_TIMESTAMP",
        "CURRENT_TRANSACTION", "CURRENT_USER", "CURRENT_VERSION", "CURRENT_WAREHOUSE", "DATEADD",
        "DATEDIFF", "DATEFROMPARTS", "DATE_FROM_PARTS", "DATE_PART", "DATE_TRUNC", "DAY", "DAYNAME",
        "DAYOFMONTH", "DAYOFWEEK", "DAYOFWEEKISO", "DAYOFYEAR", "DECODE", "DECOMPRESS_BINARY",
        "DECOMPRESS_STRING", "DECRYPT", "DECRYPT_RAW", "DEGREES", "DENSE_RANK", "DIV0", "DIV0NULL",
        "EDITDISTANCE", "ENCRYPT", "ENCRYPT_RAW", "ENDSWITH", "EQUAL_NULL", "EXP", "EXTRACT",
        "FACTORIAL", "FILTER", "FIRST_VALUE", "FLATTEN", "FLOOR", "FL_GET_CONTENT_TYPE", "FL_GET_ETAG",
        "FL_GET_FILE_TYPE", "FL_GET_LAST_MODIFIED", "FL_GET_RELATIVE_PATH", "FL_GET_SCOPED_FILE_URL",
        "FL_GET_SIZE", "FL_GET_STAGE", "FL_GET_STAGE_FILE_URL", "FL_IS_AUDIO", "FL_IS_COMPRESSED",
        "FL_IS_DOCUMENT", "FL_IS_IMAGE", "FL_IS_VIDEO", "GENERATOR", "GET", "GETBIT", "GETDATE",
        "GET_DDL", "GET_IGNORE_CASE", "GET_PATH", "GREATEST", "GREATEST_IGNORE_NULLS", "GROUPING",
        "GROUPING_ID", "HASH", "HASH_AGG", "HAVERSINE", "HEX_DECODE_BINARY", "HEX_DECODE_STRING",
        "HEX_ENCODE", "HLL", "HMAC", "HMAC_HEX", "HOUR", "IFF", "IFNULL", "ILIKE", "ILIKE_ANY", "IN",
        "INITCAP", "INSERT", "INSTR", "INVOKER_ROLE", "IS_ARRAY", "IS_BINARY", "IS_BOOLEAN", "IS_CHAR",
        "IS_DATE", "IS_DATE_VALUE", "IS_DECIMAL", "IS_DOUBLE", "IS_INTEGER", "IS_NULL_VALUE",
        "IS_OBJECT", "IS_REAL", "IS_ROLE_IN_SESSION", "IS_TIME", "IS_TIMESTAMP_LTZ", "IS_TIMESTAMP_NTZ",
        "IS_TIMESTAMP_TZ", "IS_VARCHAR", "IS_VECTOR", "JAROWINKLER_SIMILARITY",
        "JSON_EXTRACT_PATH_TEXT", "KURTOSIS", "LAG", "LAST_DAY", "LAST_QUERY_ID", "LAST_TRANSACTION",
        "LAST_VALUE", "LEAD", "LEAST", "LEAST_IGNORE_NULLS", "LEFT", "LEN", "LENGTH", "LIKE",
        "LIKE_ALL", "LIKE_ANY", "LISTAGG", "LN", "LOCALTIME", "LOCALTIMESTAMP", "LOG", "LOWER", "LPAD",
        "LTRIM", "MAP_CAT", "MAP_CONSTRUCT", "MAP_CONTAINS_KEY", "MAP_DELETE", "MAP_ENTRIES",
        "MAP_INSERT", "MAP_KEYS", "MAP_PICK", "MAP_SIZE", "MAX", "MAX_BY", "MD5", "MD5_BINARY",
        "MD5_HEX", "MD5_NUMBER_LOWER64", "MD5_NUMBER_UPPER64", "MEDIAN", "MIN", "MINUTE", "MIN_BY",
        "MOD", "MODE", "MONTH", "MONTHNAME", "MONTHS_BETWEEN", "NEGATE", "NEXT_DAY", "NORMAL",
        "NORMALIZE", "NOT", "NOW", "NTH_VALUE", "NTILE", "NULLIF", "NULLIFZERO", "NVL", "NVL2",
        "OBJECTAGG", "OBJECT_AGG", "OBJECT_CONSTRUCT", "OBJECT_CONSTRUCT_KEEP_NULL", "OBJECT_DELETE",
        "OBJECT_INSERT", "OBJECT_KEYS", "OBJECT_PICK", "OCTET_LENGTH", "OR", "PARSE_IP", "PARSE_JSON",
        "PARSE_URL", "PARSE_XML", "PERCENTILE_CONT", "PERCENTILE_DISC", "PERCENT_RANK", "PI",
        "POSITION", "POW", "POWER", "PREVIOUS_DAY", "QUARTER", "QUERY_HISTORY", "RADIANS", "RANDOM",
        "RANDSTR", "RANK", "RATIO_TO_REPORT", "REDUCE", "REGEXP", "REGEXP_COUNT", "REGEXP_EXTRACT_ALL",
        "REGEXP_INSTR", "REGEXP_LIKE", "REGEXP_REPLACE", "REGEXP_SUBSTR", "REGEXP_SUBSTR_ALL",
        "REGR_AVGX", "REGR_AVGY", "REGR_COUNT", "REGR_INTERCEPT", "REGR_R2", "REGR_SLOPE", "REGR_SXX",
        "REGR_SXY", "REGR_SYY", "REGR_VALX", "REGR_VALY", "REPEAT", "REPLACE", "RESULT_SCAN", "REVERSE",
        "RIGHT", "RLIKE", "ROUND", "ROW_NUMBER", "RPAD", "RTRIM", "RTRIMMED_LENGTH", "SEARCH", "SECOND",
        "SEQ1", "SEQ2", "SEQ4", "SEQ8", "SHA1", "SHA1_BINARY", "SHA1_HEX", "SHA2", "SHA2_BINARY",
        "SHA2_HEX", "SIGN", "SIN", "SINH", "SKEW", "SOUNDEX", "SPACE", "SPLIT", "SPLIT_PART",
        "SPLIT_TO_TABLE", "SQRT", "SQUARE", "STARTSWITH", "STDDEV", "STDDEV_POP", "STDDEV_SAMP",
        "STRING_AS_BINARY", "STRIP_NULL_VALUE", "STRTOK", "STRTOK_TO_ARRAY", "ST_AREA", "ST_ASBINARY",
        "ST_ASGEOJSON", "ST_ASTEXT", "ST_ASWKB", "ST_ASWKT", "ST_CENTROID", "ST_CONTAINS",
        "ST_DIMENSION", "ST_DISJOINT", "ST_DISTANCE", "ST_DWITHIN", "ST_GEOGFROMTEXT",
        "ST_GEOGRAPHYFROMWKT", "ST_GEOMETRYFROMWKT", "ST_GEOMFROMTEXT", "ST_GEOM_POINT",
        "ST_INTERSECTS", "ST_LENGTH", "ST_MAKEGEOMPOINT", "ST_MAKEPOINT", "ST_NPOINTS", "ST_NUMPOINTS",
        "ST_PERIMETER", "ST_POINT", "ST_SRID", "ST_WITHIN", "ST_X", "ST_XMAX", "ST_XMIN", "ST_Y",
        "ST_YMAX", "ST_YMIN", "SUBSTR", "SUBSTRING", "SUM", "SYSDATE", "SYSTIMESTAMP", "TAG_REFERENCES",
        "TAN", "TANH", "TASK_HISTORY", "TIMEADD", "TIMEDIFF", "TIMEFROMPARTS", "TIMESTAMPADD",
        "TIMESTAMPDIFF", "TIMESTAMPFROMPARTS", "TIMESTAMPLTZFROMPARTS", "TIMESTAMPNTZFROMPARTS",
        "TIMESTAMPTZFROMPARTS", "TIMESTAMP_FROM_PARTS", "TIMESTAMP_LTZ_FROM_PARTS",
        "TIMESTAMP_NTZ_FROM_PARTS", "TIMESTAMP_TZ_FROM_PARTS", "TIME_FROM_PARTS", "TIME_SLICE",
        "TO_ARRAY", "TO_BINARY", "TO_BOOLEAN", "TO_CHAR", "TO_DATE", "TO_DECFLOAT", "TO_DECIMAL",
        "TO_DOUBLE", "TO_FILE", "TO_GEOGRAPHY", "TO_GEOMETRY", "TO_INTEGER", "TO_JSON", "TO_NUMBER",
        "TO_NUMERIC", "TO_OBJECT", "TO_QUERY", "TO_TIME", "TO_TIMESTAMP", "TO_TIMESTAMP_LTZ",
        "TO_TIMESTAMP_NTZ", "TO_TIMESTAMP_TZ", "TO_UUID", "TO_VARCHAR", "TO_VARIANT", "TO_XML",
        "TRANSFORM", "TRANSLATE", "TRIM", "TRUNC", "TRUNCATE", "TRY_BASE64_DECODE_BINARY",
        "TRY_BASE64_DECODE_STRING", "TRY_CAST", "TRY_DECRYPT", "TRY_DECRYPT_RAW",
        "TRY_HEX_DECODE_BINARY", "TRY_HEX_DECODE_STRING", "TRY_PARSE_IP", "TRY_PARSE_JSON",
        "TRY_TO_BINARY", "TRY_TO_BOOLEAN", "TRY_TO_DATE", "TRY_TO_DECFLOAT", "TRY_TO_DECIMAL",
        "TRY_TO_DOUBLE", "TRY_TO_FILE", "TRY_TO_GEOGRAPHY", "TRY_TO_GEOMETRY", "TRY_TO_NUMBER",
        "TRY_TO_NUMERIC", "TRY_TO_TIME", "TRY_TO_TIMESTAMP", "TRY_TO_TIMESTAMP_LTZ",
        "TRY_TO_TIMESTAMP_NTZ", "TRY_TO_TIMESTAMP_TZ", "TRY_TO_UUID", "TRY_VALIDATE_UTF8", "TYPEOF",
        "UNICODE", "UNIFORM", "UPPER", "UUID_STRING", "VARIANCE", "VARIANCE_POP", "VARIANCE_SAMP",
        "VAR_POP", "VAR_SAMP", "VECTOR_AVG", "VECTOR_COSINE_SIMILARITY", "VECTOR_INNER_PRODUCT",
        "VECTOR_L1_DISTANCE", "VECTOR_L2_DISTANCE", "VECTOR_MAX", "VECTOR_MIN", "VECTOR_NORMALIZE",
        "VECTOR_SUM", "VECTOR_TRUNC", "VECTOR_TRUNCATE", "WEEK", "WEEKISO", "WEEKOFYEAR",
        "WIDTH_BUCKET", "XMLGET", "YEAR", "YEAROFWEEK", "YEAROFWEEKISO", "ZEROIFNULL"
    };

    /** The grammar's data-type names, including the Snowflake spellings and aliases (46). */
    private static final String[] FROSTLAKE_TYPES = {
        "ARRAY", "BIGINT", "BINARY", "BOOLEAN", "BYTEINT", "CHAR", "CHARACTER", "DATE", "DATETIME",
        "DEC", "DECFLOAT", "DECIMAL", "DOUBLE", "FILE", "FLOAT", "FLOAT4", "FLOAT8", "GEOGRAPHY",
        "GEOMETRY", "INT", "INTEGER", "MAP", "NCHAR", "NUMBER", "NUMERIC", "NVARCHAR", "NVARCHAR2",
        "OBJECT", "REAL", "SMALLINT", "STRING", "TEXT", "TIME", "TIMESTAMP", "TIMESTAMPLTZ",
        "TIMESTAMPNTZ", "TIMESTAMPTZ", "TIMESTAMP_LTZ", "TIMESTAMP_NTZ", "TIMESTAMP_TZ", "TINYINT",
        "UUID", "VARBINARY", "VARCHAR", "VARIANT", "VECTOR"
    };

    public FrostlakeSQLDialect() {
        super("Frostlake", "frostlake");
    }

    @Override
    public void initDriverSettings(JDBCSession session, JDBCDataSource dataSource, JDBCDatabaseMetaData metaData) {
        super.initDriverSettings(session, dataSource, metaData);
        addSQLKeywords(Arrays.asList(FROSTLAKE_KEYWORDS));
        addFunctions(Arrays.asList(FROSTLAKE_FUNCTIONS));
        addDataTypes(Arrays.asList(FROSTLAKE_TYPES));
    }

    @Override
    public String[][] getBlockBoundStrings() {
        return new String[][]{{"BEGIN", "END"}};
    }

    @Override
    public boolean supportsAliasInSelect() {
        return true;
    }

    @Override
    public boolean supportsTableDropCascade() {
        return false;
    }
}
