/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.doris.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.Log;
import org.jkiss.dbeaver.ext.generic.model.GenericTableBase;
import org.jkiss.dbeaver.ext.generic.model.GenericTableColumn;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
import org.jkiss.dbeaver.model.impl.jdbc.JDBCUtils;
import org.jkiss.utils.CommonUtils;

import java.sql.Types;

/**
 * Doris Table Column - represents a column in a Doris table or view.
 * Parses column metadata from SHOW FULL COLUMNS result set.
 */
public class DorisTableColumn extends GenericTableColumn {

    private static final Log log = Log.getLog(DorisTableColumn.class);

    private static final String COL_COLUMN_NAME = "COLUMN_NAME"; //$NON-NLS-1$
    private static final String COL_COLUMN_TYPE = "COLUMN_TYPE"; //$NON-NLS-1$
    private static final String COL_IS_NULLABLE = "IS_NULLABLE"; //$NON-NLS-1$
    private static final String COL_COLUMN_DEFAULT = "COLUMN_DEFAULT"; //$NON-NLS-1$
    private static final String COL_COLUMN_COMMENT = "COLUMN_COMMENT"; //$NON-NLS-1$

    public DorisTableColumn(@NotNull GenericTableBase table) {
        super(table);
    }

    /**
     * Constructs a column by parsing information_schema.columns result set.
     */
    public DorisTableColumn(
        @NotNull GenericTableBase table,
        @NotNull JDBCResultSet dbResult,
        int ordinal
    ) {
        super(table,
            JDBCUtils.safeGetString(dbResult, COL_COLUMN_NAME),
            JDBCUtils.safeGetString(dbResult, COL_COLUMN_TYPE),
            mapSqlType(JDBCUtils.safeGetString(dbResult, COL_COLUMN_TYPE), null),
            Types.OTHER,
            ordinal,
            extractColumnSize(JDBCUtils.safeGetString(dbResult, COL_COLUMN_TYPE), null),
            extractColumnSize(JDBCUtils.safeGetString(dbResult, COL_COLUMN_TYPE), null),
            extractScale(JDBCUtils.safeGetString(dbResult, COL_COLUMN_TYPE), null),
            null,
            10,
            "NO".equalsIgnoreCase(JDBCUtils.safeGetString(dbResult, COL_IS_NULLABLE)),
            JDBCUtils.safeGetString(dbResult, COL_COLUMN_COMMENT),
            JDBCUtils.safeGetString(dbResult, COL_COLUMN_DEFAULT),
            false,
            false
        );
    }

    /**
     * Constructs a column with basic properties (for manual creation).
     */
    public DorisTableColumn(
        @NotNull GenericTableBase table,
        @NotNull String columnName,
        @NotNull String typeName,
        int valueType,
        int sourceType,
        int ordinalPosition,
        long columnSize,
        long charLength,
        @Nullable Integer scale,
        @Nullable Integer precision,
        int radix,
        boolean notNull,
        @Nullable String remarks,
        @Nullable String defaultValue,
        boolean autoIncrement,
        boolean autoGenerated
    ) throws DBException {
        super(table,
            columnName,
            typeName,
            mapSqlType(typeName, valueType),
            sourceType,
            ordinalPosition,
            extractColumnSize(typeName, columnSize),
            extractColumnSize(typeName, charLength),
            extractScale(typeName, scale),
            precision,
            radix,
            notNull,
            remarks,
            defaultValue,
            autoIncrement,
            autoGenerated
        );
    }

    @NotNull
    @Override
    public DorisDataSource getDataSource() {
        return (DorisDataSource) super.getDataSource();
    }

    private static int mapSqlType(@Nullable String typeName, @Nullable Integer givenType) {
        if (typeName == null) {
            return CommonUtils.notNull(givenType, Types.OTHER);
        }
        String upperType = typeName.toUpperCase();
        int parenIndex = upperType.indexOf('(');
        if (parenIndex > 0) {
            upperType = upperType.substring(0, parenIndex).trim();
        }

        return switch (upperType) {
            case "BOOLEAN", "BOOL" -> Types.BOOLEAN;
            case "TINYINT" -> Types.TINYINT;
            case "SMALLINT" -> Types.SMALLINT;
            case "INT", "INTEGER" -> Types.INTEGER;
            case "BIGINT", "LARGEINT" -> Types.BIGINT;
            case "FLOAT" -> Types.FLOAT;
            case "DOUBLE" -> Types.DOUBLE;
            case "DECIMAL", "DECIMALV2", "DECIMAL32", "DECIMAL64", "DECIMAL128" -> Types.DECIMAL;
            case "CHAR" -> Types.CHAR;
            case "VARCHAR", "STRING", "TEXT" -> Types.VARCHAR;
            case "BINARY", "VARBINARY" -> Types.VARBINARY;
            case "DATE" -> Types.DATE;
            case "DATETIME", "TIMESTAMP" -> Types.TIMESTAMP;
            case "TIME" -> Types.TIME;
            case "ARRAY" -> Types.ARRAY;
            case "MAP", "STRUCT" -> Types.STRUCT;
            default -> CommonUtils.notNull(givenType, Types.OTHER);
        };
    }

    private static long extractColumnSize(@Nullable String typeName, @Nullable Long givenSize) {
        if (typeName == null) {
            return CommonUtils.notNull(givenSize, 0L);
        }
        int parenStart = typeName.indexOf('(');
        int parenEnd = typeName.indexOf(')');
        if (parenStart > 0 && parenEnd > parenStart) {
            String sizeStr = typeName.substring(parenStart + 1, parenEnd);
            int commaIndex = sizeStr.indexOf(',');
            if (commaIndex > 0) {
                sizeStr = sizeStr.substring(0, commaIndex);
            }
            try {
                return Long.parseLong(sizeStr.trim());
            } catch (NumberFormatException e) {
                log.debug("Failed to parse column size from type: " + typeName, e); //$NON-NLS-1$
                return CommonUtils.notNull(givenSize, 0L);
            }
        }
        return CommonUtils.notNull(givenSize, 0L);
    }

    @Nullable
    private static Integer extractScale(@Nullable String typeName, @Nullable Integer givenScale) {
        if (typeName == null) {
            return givenScale;
        }
        int parenStart = typeName.indexOf('(');
        int parenEnd = typeName.indexOf(')');
        if (parenStart > 0 && parenEnd > parenStart) {
            String sizeStr = typeName.substring(parenStart + 1, parenEnd);
            int commaIndex = sizeStr.indexOf(',');
            if (commaIndex > 0) {
                try {
                    return Integer.parseInt(sizeStr.substring(commaIndex + 1).trim());
                } catch (NumberFormatException e) {
                    log.debug("Failed to parse column scale from type: " + typeName, e); //$NON-NLS-1$
                    return givenScale;
                }
            }
        }
        return givenScale;
    }
}
