/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.model.data.resultset;

import org.jkiss.code.NotNull;
import org.jkiss.dbeaver.model.DBUtils;
import org.jkiss.dbeaver.model.data.DBDAttributeValue;
import org.jkiss.dbeaver.model.struct.DBSEntity;

import java.util.ArrayList;
import java.util.List;

public class DBDDataStatementInfo {
    protected final List<DBDAttributeValue> updateAttributes = new ArrayList<>();
    protected final List<DBDAttributeValue> keyAttributes = new ArrayList<>();
    protected final DBSEntity entity;
    protected boolean executed = false;

    public DBDDataStatementInfo(@NotNull DBSEntity entity) {
        this.entity = entity;
    }

    @NotNull
    public DBSEntity getEntity() {
        return entity;
    }

    @NotNull
    public List<DBDAttributeValue> getUpdateAttributes() {
        return updateAttributes;
    }

    @NotNull
    public List<DBDAttributeValue> getKeyAttributes() {
        return keyAttributes;
    }

    public boolean isExecuted() {
        return executed;
    }

    public void setExecuted(boolean executed) {
        this.executed = executed;
    }

    public boolean needKeys() {
        for (DBDAttributeValue col : keyAttributes) {
            if (col.getAttribute().isAutoGenerated() && DBUtils.isNullValue(col.getValue())) {
                return true;
            }
        }
        return false;
    }

}
