/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.model.data.resultset;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.DBException;
import org.jkiss.dbeaver.model.DBPDataSource;
import org.jkiss.dbeaver.model.DBPDataSourceInfo;
import org.jkiss.dbeaver.model.data.*;
import org.jkiss.dbeaver.model.data.messages.DataMessages;
import org.jkiss.dbeaver.model.exec.DBCExecutionContext;
import org.jkiss.dbeaver.model.exec.DBCExecutionPurpose;
import org.jkiss.dbeaver.model.exec.DBCExecutionSource;
import org.jkiss.dbeaver.model.exec.DBCSession;
import org.jkiss.dbeaver.model.runtime.DBRProgressMonitor;
import org.jkiss.dbeaver.model.runtime.VoidProgressMonitor;
import org.jkiss.dbeaver.model.struct.DBSDataManipulator;
import org.jkiss.dbeaver.model.struct.DBSEntity;
import org.jkiss.dbeaver.model.struct.rdb.DBSManipulationType;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.List;
import java.util.Map;

public class DBDResultSetDataUpdaterTest {

    @Test
    public void explicitNullIsIncludedInInsert() throws Exception {
        DBDResultSetModel model = Mockito.mock(DBDResultSetModel.class);
        DBDValueRow row = Mockito.mock(DBDValueRow.class);
        DBSEntity entity = Mockito.mock(DBSEntity.class);
        DBDAttributeBinding nullableAttribute = Mockito.mock(DBDAttributeBinding.class);
        DBDAttributeBinding generatedAttribute = Mockito.mock(DBDAttributeBinding.class);

        Mockito.when(model.getSingleSource()).thenReturn(entity);
        Mockito.when(model.getAttributes()).thenReturn(new DBDAttributeBinding[] {nullableAttribute, generatedAttribute});
        Mockito.when(model.getCellValue(nullableAttribute, row)).thenReturn(null);
        Mockito.when(model.getCellValue(generatedAttribute, row)).thenReturn(null);
        Mockito.when(generatedAttribute.isAutoGenerated()).thenReturn(true);

        TestDataUpdater updater = new TestDataUpdater(model, row);
        updater.prepareStatements(new VoidProgressMonitor(), new ResultSetSaveSettings());

        DBDDataStatementInfo statement = updater.getInsertStatements().getFirst();
        Assertions.assertEquals(2, statement.getKeyAttributes().size());
        Assertions.assertSame(nullableAttribute, statement.getKeyAttributes().getFirst().getAttribute());
        Assertions.assertNull(statement.getKeyAttributes().getFirst().getValue());
        Assertions.assertSame(generatedAttribute, statement.getKeyAttributes().getLast().getAttribute());
        Assertions.assertNull(statement.getKeyAttributes().getLast().getValue());
        Assertions.assertTrue(statement.needKeys());
    }

    @Test
    public void repeatedPreparationDoesNotDuplicateStatements() throws Exception {
        DBDResultSetModel model = Mockito.mock(DBDResultSetModel.class);
        DBDValueRow row = Mockito.mock(DBDValueRow.class);
        DBSEntity entity = Mockito.mock(DBSEntity.class);

        Mockito.when(model.getSingleSource()).thenReturn(entity);
        Mockito.when(model.getAttributes()).thenReturn(new DBDAttributeBinding[0]);

        TestDataUpdater updater = new TestDataUpdater(model, row);
        ResultSetSaveSettings settings = new ResultSetSaveSettings();
        updater.prepareStatements(new VoidProgressMonitor(), settings);
        updater.prepareStatements(new VoidProgressMonitor(), settings);

        Assertions.assertEquals(1, updater.getInsertStatements().size());
    }

    @Test
    public void customDocumentValueIsUsedForInsert() throws Exception {
        DBDResultSetModel model = Mockito.mock(DBDResultSetModel.class);
        DBDValueRow row = Mockito.mock(DBDValueRow.class);
        DBSEntity entity = Mockito.mock(DBSEntity.class);
        DBDAttributeBinding documentAttribute = Mockito.mock(DBDAttributeBinding.class);
        Object documentValue = new Object();

        Mockito.when(model.getSingleSource()).thenReturn(entity);
        Mockito.when(model.getDocumentAttribute()).thenReturn(documentAttribute);

        TestDataUpdater updater = new TestDataUpdater(model, row);
        updater.setInsertDocumentValue(documentValue);
        updater.prepareStatements(new VoidProgressMonitor(), new ResultSetSaveSettings());

        DBDAttributeValue attributeValue = updater.getInsertStatements().getFirst().getKeyAttributes().getFirst();
        Assertions.assertSame(documentAttribute, attributeValue.getAttribute());
        Assertions.assertSame(documentValue, attributeValue.getValue());
    }

    @Test
    public void customKeyAttributeAndValueAreUsedForDelete() throws Exception {
        DBDResultSetModel model = Mockito.mock(DBDResultSetModel.class);
        DBDValueRow row = Mockito.mock(DBDValueRow.class);
        DBSEntity entity = Mockito.mock(
            DBSEntity.class,
            Mockito.withSettings().extraInterfaces(DBSDataManipulator.class)
        );
        DBPDataSource dataSource = Mockito.mock(DBPDataSource.class);
        DBPDataSourceInfo dataSourceInfo = Mockito.mock(DBPDataSourceInfo.class);
        DBDRowIdentifier identifier = Mockito.mock(DBDRowIdentifier.class);
        DBDAttributeBinding keyAttribute = Mockito.mock(DBDAttributeBinding.class);

        Mockito.when(model.getDefaultRowIdentifier()).thenReturn(identifier);
        Mockito.when(identifier.getEntity()).thenReturn(entity);
        Mockito.when(identifier.getAttributes()).thenReturn(List.of(keyAttribute));
        Mockito.when(entity.getDataSource()).thenReturn(dataSource);
        Mockito.when(dataSource.getInfo()).thenReturn(dataSourceInfo);

        DBDAttributeBinding deleteKeyAttribute = Mockito.mock(DBDAttributeBinding.class);
        Object keyValue = new Object();
        TestDataUpdater updater = new TestDataUpdater(model, row);
        updater.prepareDelete(row, deleteKeyAttribute, keyValue);
        updater.prepareStatements(new VoidProgressMonitor(), new ResultSetSaveSettings());

        DBDDataStatementInfo statement = updater.getDeleteStatements().getFirst();
        Assertions.assertSame(deleteKeyAttribute, statement.getKeyAttributes().getFirst().getAttribute());
        Assertions.assertSame(keyValue, statement.getKeyAttributes().getFirst().getValue());
    }

    @Test
    public void canceledExecutionLeavesStatementPendingWithoutError() throws Exception {
        DBDResultSetModel model = Mockito.mock(DBDResultSetModel.class);
        DBDValueRow row = Mockito.mock(DBDValueRow.class);
        DBSEntity entity = Mockito.mock(DBSEntity.class);
        DBCExecutionContext executionContext = Mockito.mock(DBCExecutionContext.class);
        DBCSession session = Mockito.mock(DBCSession.class);
        DBRProgressMonitor monitor = Mockito.mock(DBRProgressMonitor.class);
        DBPDataSource dataSource = Mockito.mock(DBPDataSource.class, Mockito.RETURNS_DEEP_STUBS);

        Mockito.when(model.getSingleSource()).thenReturn(entity);
        Mockito.when(model.getAttributes()).thenReturn(new DBDAttributeBinding[0]);
        Mockito.when(executionContext.openSession(
            monitor,
            DBCExecutionPurpose.USER,
            DataMessages.controls_resultset_viewer_job_update
        )).thenReturn(session);
        Mockito.when(session.getDataSource()).thenReturn(dataSource);
        Mockito.when(session.getProgressMonitor()).thenReturn(monitor);
        Mockito.when(monitor.isCanceled()).thenReturn(true);

        TestDataUpdater updater = new TestDataUpdater(model, row, executionContext);
        updater.prepareStatements(monitor, new ResultSetSaveSettings());

        Assertions.assertNull(updater.executeStatements(monitor, Map.of(), null, false));
        Assertions.assertFalse(updater.getInsertStatements().getFirst().isExecuted());
    }

    private static class TestDataUpdater extends DBDResultSetDataUpdater<DBDDataStatementInfo, DBDValueRow, DBDResultSetModel> {
        private Object keyValue;
        private DBDAttributeBinding deleteKeyAttribute;
        private boolean useCustomKeyValue;
        private Object insertDocumentValue;

        private TestDataUpdater(@NotNull DBDResultSetModel model, @NotNull DBDValueRow row) {
            this(model, row, null);
        }

        private TestDataUpdater(
            @NotNull DBDResultSetModel model,
            @NotNull DBDValueRow row,
            @Nullable DBCExecutionContext executionContext
        ) {
            super(model, executionContext);
            addedRows.add(row);
        }

        @NotNull
        private List<DBDDataStatementInfo> getInsertStatements() {
            return insertStatements;
        }

        @NotNull
        private List<DBDDataStatementInfo> getDeleteStatements() {
            return deleteStatements;
        }

        private void prepareDelete(
            @NotNull DBDValueRow row,
            @NotNull DBDAttributeBinding deleteKeyAttribute,
            @Nullable Object keyValue
        ) {
            addedRows.clear();
            deletedRows.add(row);
            this.deleteKeyAttribute = deleteKeyAttribute;
            this.keyValue = keyValue;
            useCustomKeyValue = true;
        }

        private void setInsertDocumentValue(@Nullable Object insertDocumentValue) {
            this.insertDocumentValue = insertDocumentValue;
        }

        @NotNull
        @Override
        protected DBDDataStatementInfo getDataStatementInfo(
            @NotNull DBSManipulationType type,
            @NotNull DBDValueRow row,
            @NotNull DBSEntity entity
        ) {
            return new DBDDataStatementInfo(entity);
        }

        @Nullable
        @Override
        protected Map<DBDAttributeBinding, Object> collectUpdateChanges(@NotNull DBDValueRow row) {
            return null;
        }

        @Nullable
        @Override
        protected Object getKeyValue(@NotNull DBDAttributeBinding attribute, @NotNull DBDValueRow row) throws DBException {
            return useCustomKeyValue ? keyValue : super.getKeyValue(attribute, row);
        }

        @Nullable
        @Override
        protected Object getInsertDocumentValue(
            @NotNull DBDAttributeBinding attribute,
            @NotNull DBDValueRow row
        ) throws DBException {
            return insertDocumentValue == null ? super.getInsertDocumentValue(attribute, row) : insertDocumentValue;
        }

        @NotNull
        @Override
        protected DBDAttributeValue getDeleteKeyAttributeValue(
            @NotNull DBDAttributeBinding attribute,
            @NotNull DBDValueRow row
        ) throws DBException {
            if (deleteKeyAttribute != null) {
                return new DBDAttributeValue(deleteKeyAttribute, getKeyValue(attribute, row));
            }
            return super.getDeleteKeyAttributeValue(attribute, row);
        }

        @Override
        protected void collectUpdatedRows() {
        }

        @NotNull
        @Override
        protected DBCExecutionSource createExecutionSource(@NotNull DBSDataManipulator dataContainer) {
            throw new UnsupportedOperationException();
        }

        @Nullable
        @Override
        protected DBDDataReceiver getKeyReceiver(@NotNull DBDDataStatementInfo statement) {
            return null;
        }
    }
}
