name: dbeaver-ce
version: latest
summary: Universal Database Tool
description: |
  Free multi-platform database tool for developers, SQL programmers,
  database administrators and analysts. Supports all popular databases
  MySQL, PostgreSQL, MariaDB, SQLite, Oracle, DB2, SQL Server, Sybase,
  MS Access, Teradata, Firebird, Derby, etc.
grade: stable
confinement: strict
architectures:
  - build-on: [amd64, i386]
    run-on: amd64

apps:
  dbeaver-ce:
    command: desktop-launch $SNAP/usr/share/dbeaver/dbeaver
    desktop: usr/share/applications/dbeaver.desktop
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
      FONTCONFIG_FILE: $SNAP/etc/fonts
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA
    plugs:
      - desktop
      - network
      - x11
      - home
      - desktop-legacy

parts:
  dbeaver-ce:
    source: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
    plugin: dump
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre
    stage-packages:
      - openjdk-8-jre
      - libswt-gtk-3-java
      - x11-xserver-utils
      - libxss1
      - libgconf2-4
      - libcurl3
      - libgtk-3-dev
      - xdg-utils
    override-build: |
      snapcraftctl build
      DEB_API="https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f6)
      echo $VERSION > $SNAPCRAFT_STAGE/version
      # Correct path to icon.
      sed -i 's|Icon=dbeaver|Icon=/usr/share/dbeaver/dbeaver\.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/dbeaver.desktop

  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - gcc
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
      
plugs:
  # GTK libraries
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  # Common GTK themes
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
