/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2026 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.h2.model;

import org.jkiss.code.NotNull;
import org.jkiss.code.Nullable;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCObjectSupplier;
import org.jkiss.dbeaver.model.exec.jdbc.JDBCResultSet;
import org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl;

import java.sql.SQLException;
import java.sql.Statement;

final class H2StatementImpl extends JDBCStatementImpl<Statement> {
    H2StatementImpl(
        @NotNull H2ConnectionImpl connection,
        @NotNull JDBCObjectSupplier<Statement> original,
        boolean disableLogging
    ) throws SQLException {
        super(connection, original, null, disableLogging);
    }

    @Override
    public boolean execute(@NotNull String sql) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.execute(sql);
    }

    @Nullable
    @Override
    public JDBCResultSet executeQuery(@NotNull String sql) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.executeQuery(sql);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.executeUpdate(sql);
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.executeUpdate(sql, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.executeUpdate(sql, columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.executeUpdate(sql, columnNames);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.execute(sql, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.execute(sql, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        return super.execute(sql, columnNames);
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        H2ConnectionImpl.validateQuery(sql);
        super.addBatch(sql);
    }
}
