name: "Commit Message Validation"

on:
  pull_request:
    branches:
      - devel
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
      - labeled

permissions:
  contents: read

jobs:
  check-commit-message:
    permissions:
      contents: none
    uses: dbeaver/dbeaver/.github/workflows/reused-commit-msgs-validator.yml@devel