name: "Commit Message Validation"

on:
  pull_request:
    branches:
      - devel
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
      - labeled

jobs:
  check-commit-message:
    uses: dbeaver/dbeaver/.github/workflows/reused-commit-msgs-validator.yml@devel