name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [devel]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Clone repo and dependencies, prerare Java and Maven
        uses: dbeaver/github-actions/prepare-for-a-maven-lifecycle@devel
        with:
          project-deps: ./dbeaver/project.deps
          token: ${{ secrets.DEVOPS_ISSUE_RO_TOKEN }}

      - name: Prepare custom p2
        uses: dbeaver/github-actions/prepare-custom-p2@dbeaver/dbeaver-devops#2023-custom-p2 # CHANGEME after PR approval
        if: ${{ github.event_name == 'pull_request' }}
        id: prepare-p2
        with:
          repo: "dbeaver-deps-ce"

      - name: Build DBeaver
        run: |
          if [ ${{ steps.prepare-p2.outputs.p2-found }} = 'true' ]; then
            p2_repo='./dbeaver-deps-ce/p2/repository/target/repository'
            p2_uri="file://$(realpath "$p2_repo")"
            echo "p2_uri=$p2_uri"
            mvn clean verify -B -T1C ${{ inputs.mvn-args }} -Drepo.p2.dbeaver-ce.url="$p2_uri" -f './dbeaver/product/aggregate'
          else
            mvn clean verify -B -T1C ${{ inputs.mvn-args }} -f './dbeaver/product/aggregate'
          fi

  lint-java:
    name: Check style
    uses: dbeaver/dbeaver-common/.github/workflows/java-checkstyle.yml@devel
    secrets: inherit
