name: PR Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [devel]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Clone repo and dependencies, prerare Java and Maven
        uses: dbeaver/github-actions/prepare-for-a-maven-lifecycle@devel
        with:
          project-deps: ./dbeaver/project.deps
          token: ${{ secrets.DEVOPS_ISSUE_RO_TOKEN }}

      - name: Prepare custom p2
        uses: dbeaver/github-actions/prepare-custom-p2@dbeaver/dbeaver-devops#2023-custom-p2 # CHANGEME after PR approval
        if: ${{ github.event_name == 'pull_request' }}
        id: prepare-p2
        with:
          repo: "dbeaver-deps-ce"
          mvn-property: "repo.p2.dbeaver-ce.url"

      - name: Build DBeaver
        working-directory: ./dbeaver/product/aggregate
        run: mvn clean verify -B -T1C {{ steps.prepare-p2.outputs.mvn-flag }}

  lint-java:
    name: Check style
    uses: dbeaver/dbeaver-common/.github/workflows/java-checkstyle.yml@devel
    secrets: inherit
