/*
 * DBeaver - Universal Database Manager
 * Copyright (C) 2010-2023 DBeaver Corp and others
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jkiss.dbeaver.ext.postgresql.model;

public class PostgreKeywords {

    public static String[] POSTGRE_EXTRA_KEYWORDS = new String[]{
        "ABSENT",
        "ACCORDING",
        "ADA",
        "ADMIN",
        //            "ARRAY_AGG",
        //            "ARRAY_MAX_CARDINALITY",
        "BASE64",
        "BEGIN_FRAME",
        "BEGIN_PARTITION",
        "BERNOULLI",
        "BIT_LENGTH",
        "BLOCKED",
        "BOM",
        //"BREADTH",
        //            "CATALOG_NAME",
        //            "CHARACTER_SET_CATALOG",
        //            "CHARACTER_SET_NAME",
        //            "CHARACTER_SET_SCHEMA",
        //            "CLASS_ORIGIN",
        //"COBOL",
        //            "COLLATION_CATALOG",
        //            "COLLATION_NAME",
        //            "COLLATION_SCHEMA",
        //            "COLUMN_NAME",
        //            "COMMAND_FUNCTION",
        //            "COMMAND_FUNCTION_CODE",
        //            "CONDITION_NUMBER",
        //            "CONNECTION_NAME",
        //            "CONSTRAINT_CATALOG",
        //            "CONSTRAINT_NAME",
        //            "CONSTRAINT_SCHEMA",
        "CONTROL",
        //            "CURRENT_ROW",
        //            "DATALINK",
        //            "DATETIME_INTERVAL_CODE",
        //            "DATETIME_INTERVAL_PRECISION",
        //"DB",
        "DLNEWCOPY",
        "DLPREVIOUSCOPY",
        "DLURLCOMPLETE",
        "DLURLCOMPLETEONLY",
        "DLURLCOMPLETEWRITE",
        "DLURLPATH",
        "DLURLPATHONLY",
        "DLURLPATHWRITE",
        "DLURLSCHEME",
        "DLURLSERVER",
        "DLVALUE",
        "DYNAMIC_FUNCTION",
        "DYNAMIC_FUNCTION_CODE",
        "EMPTY",
        "END_FRAME",
        "END_PARTITION",
        "ENFORCED",
        "EXIT",
        "EXPRESSION",
        //"FILE",
        "FIRST_VALUE",
        //"FLAG",
        //"FORTRAN",
        "FRAME_ROW",
        "FS",
        "GROUPS",
        //"HEX",
        //"ID",
        "IGNORE",
        "IMMEDIATELY",
        "INCLUDE",
        "INDENT",
        "INTEGRITY",
        "KEY_MEMBER",
        "LAG",
        "LAST_VALUE",
        "LEAD",
        "LIBRARY",
        "LIKE_REGEX",
        //"LINK",
        //            "MAX_CARDINALITY",
        //            "MESSAGE_LENGTH",
        //            "MESSAGE_OCTET_LENGTH",
        //            "MESSAGE_TEXT",
        //"MODULE",
        //"NAME",
        //"NAMES",
        "NAMESPACE",
        //"NFC",
        //"NFD",
        //"NFKC",
        //"NFKD",
        "NIL",
        "NTH_VALUE",
        "NTILE",
        "NULLABLE",
        "OCCURRENCES_REGEX",
        //            "PARAMETER_MODE",
        //            "PARAMETER_NAME",
        //            "PARAMETER_ORDINAL_POSITION",
        //            "PARAMETER_SPECIFIC_CATALOG",
        //            "PARAMETER_SPECIFIC_NAME",
        //            "PARAMETER_SPECIFIC_SCHEMA",
        //"PASCAL",
        "PASSTHROUGH",
        "PERCENT",
        "PERIOD",
        "PERMISSION",
        //"PLI",
        //"PORTION",
        "POSITION_REGEX",
        "PRECEDES",
        "PROCEDURES",
        //"PUBLIC",
        "RECOVERY",
        "REQUIRING",
        "RESPECT",
        "RESTORE",
        "RULE",
        //            "RETURNED_CARDINALITY",
        //            "RETURNED_LENGTH",
        //            "RETURNED_OCTET_LENGTH",
        //            "RETURNED_SQLSTATE",
        //            "ROUTINES",
        //            "ROUTINE_CATALOG",
        //            "ROUTINE_NAME",
        //            "ROUTINE_SCHEMA",
        //"ROW_COUNT",
        //"SCHEMA_NAME",
        //"SCOPE_CATALOG",
        //"SCOPE_NAME",
        //"SCOPE_SCHEMA",
        //"SELECTIVE",
        //"SERVER_NAME",
        "SIMPLE",
        //"SPECIFIC_NAME",
        "SQLCODE",
        "SQLERROR",
        //"STATE",
        //"SUBCLASS_ORIGIN",
        //"SUBSTRING_REGEX",
        "SUCCEEDS",
        //"SYSTEM_TIME",
        //"TABLE_NAME",
        "TOKEN",
        //"TOP_LEVEL_COUNT",
        //"TRANSACTIONS_COMMITTED",
        //"TRANSACTIONS_ROLLED_BACK",
        //"TRANSACTION_ACTIVE",
        //"TRANSLATE_REGEX",
        //"TRIGGER_CATALOG",
        //"TRIGGER_NAME",
        //"TRIGGER_SCHEMA",
        //"TRIM_ARRAY",
        "UNLINK",
        "UNTYPED",
        //"URI",
        //"USER_DEFINED_TYPE_CATALOG",
        //"USER_DEFINED_TYPE_CODE",
        //"USER_DEFINED_TYPE_NAME",
        //"USER_DEFINED_TYPE_SCHEMA",
        //"VALUE",
        //"VALUE_OF",
        "VERSIONING",
        "XMLAGG",
        "XMLBINARY",
        "XMLCAST",
        "XMLCOMMENT",
        "XMLDECLARATION",
        "XMLDOCUMENT",
        "XMLITERATE",
        "XMLQUERY",
        "XMLSCHEMA",
        "XMLTEXT",
        "XMLVALIDATE",
        "SQLERRM",
        "WHILE"
    };

    public static String[] POSTGRE_ONE_CHAR_KEYWORDS = new String[]{
        "C",
        "G",
        "K",
        "M",
        "T",
        "P"
    };

    public static String[] POSTGRE_FUNCTIONS_AGGREGATE = new String[]{
        "ARRAY_AGG",
        "BIT_AND",
        "BIT_OR",
        "BOOL_AND",
        "BOOL_OR",
        "EVERY",
        "JSON_AGG",
        "JSONB_AGG",
        "JSON_OBJECT_AGG",
        "JSONB_OBJECT_AGG",
        "MODE",
        "STRING_AGG",
        "XMLAGG",
        "CORR",
        "COVAR_POP",
        "COVAR_SAMP",
        "STDDEV",
        "STDDEV_POP",
        "STDDEV_SAMP",
        "VARIANCE",
        "VAR_POP",
        "VAR_SAMP"
    };

    public static String[] POSTGRE_FUNCTIONS_STRING = new String[]{
        "BIT_LENGTH",
        "BTRIM",
        "CHR",
        "CONCAT_WS",
        "CONVERT",
        "CONVERT_FROM",
        "CONVERT_TO",
        "DECODE",
        "ENCODE",
        "INITCAP",
        "LEFT",
        "LENGTH",
        "LPAD",
        "MD5",
        "OVERLAY",
        "PARSE_IDENT",
        "PG_CLIENT_ENCODING",
        "POSITION",
        "QUOTE_IDENT",
        "QUOTE_LITERAL",
        "QUOTE_NULLABLE",
        "REGEXP_MATCH",
        "REGEXP_MATCHES",
        "REGEXP_REPLACE",
        "REGEXP_SPLIT_TO_ARRAY",
        "REGEXP_SPLIT_TO_TABLE",
        "REPLACE",
        "REVERSE",
        "RIGHT",
        "RPAD",
        "SPLIT_PART",
        "STRPOS",
        "SUBSTRING",
        "TO_ASCII",
        "TO_HEX",
        "TRANSLATE",
        "TREAT",
        "UNACCENT"
    };

    public static String[] POSTGRE_FUNCTIONS_XML = new String[]{
        "XMLCOMMENT",
        "XMLCONCAT",
        "XMLELEMENT",
        "XMLFOREST",
        "XMLPI",
        "XMLROOT",
        "XMLEXISTS",
        "XML_IS_WELL_FORMED",
        "XML_IS_WELL_FORMED_DOCUMENT",
        "XML_IS_WELL_FORMED_CONTENT",
        "XPATH",
        "XPATH_EXISTS",
        "XMLTABLE",
        "XMLNAMESPACES",
        "TABLE_TO_XML",
        "TABLE_TO_XMLSCHEMA",
        "TABLE_TO_XML_AND_XMLSCHEMA",
        "QUERY_TO_XML",
        "QUERY_TO_XMLSCHEMA",
        "QUERY_TO_XML_AND_XMLSCHEMA",
        "CURSOR_TO_XML",
        "CURSOR_TO_XMLSCHEMA",
        "SCHEMA_TO_XML",
        "SCHEMA_TO_XMLSCHEMA",
        "SCHEMA_TO_XML_AND_XMLSCHEMA",
        "DATABASE_TO_XML",
        "DATABASE_TO_XMLSCHEMA",
        "DATABASE_TO_XML_AND_XMLSCHEMA",
        "XMLATTRIBUTES"
    };

    public static String[] POSTGRE_FUNCTIONS_JSON = new String[]{
        "TO_JSON",
        "TO_JSONB",
        "ARRAY_TO_JSON",
        "ROW_TO_JSON",
        "JSON_BUILD_ARRAY",
        "JSONB_BUILD_ARRAY",
        "JSON_BUILD_OBJECT",
        "JSONB_BUILD_OBJECT",
        "JSON_OBJECT",
        "JSONB_OBJECT",
        "JSON_ARRAY_LENGTH",
        "JSONB_ARRAY_LENGTH",
        "JSON_EACH",
        "JSONB_EACH",
        "JSON_EACH_TEXT",
        "JSONB_EACH_TEXT",
        "JSON_EXTRACT_PATH",
        "JSONB_EXTRACT_PATH",
        "JSON_OBJECT_KEYS",
        "JSONB_OBJECT_KEYS",
        "JSON_POPULATE_RECORD",
        "JSONB_POPULATE_RECORD",
        "JSON_POPULATE_RECORDSET",
        "JSONB_POPULATE_RECORDSET",
        "JSON_ARRAY_ELEMENTS",
        "JSONB_ARRAY_ELEMENTS",
        "JSON_ARRAY_ELEMENTS_TEXT",
        "JSONB_ARRAY_ELEMENTS_TEXT",
        "JSON_TYPEOF",
        "JSONB_TYPEOF",
        "JSON_TO_RECORD",
        "JSONB_TO_RECORD",
        "JSON_TO_RECORDSET",
        "JSONB_TO_RECORDSET",
        "JSON_STRIP_NULLS",
        "JSONB_STRIP_NULLS",
        "JSONB_SET",
        "JSONB_INSERT",
        "JSONB_PRETTY"
    };

    public static String[] POSTGRE_FUNCTIONS_ARRAY = new String[]{
        "ARRAY_APPEND",
        "ARRAY_CAT",
        "ARRAY_NDIMS",
        "ARRAY_DIMS",
        "ARRAY_FILL",
        "ARRAY_LENGTH",
        "ARRAY_LOWER",
        "ARRAY_POSITION",
        "ARRAY_POSITIONS",
        "ARRAY_PREPEND",
        "ARRAY_REMOVE",
        "ARRAY_REPLACE",
        "ARRAY_TO_STRING",
        "ARRAY_UPPER",
        "CARDINALITY",
        "STRING_TO_ARRAY",
        "UNNEST"
    };

    public static String[] POSTGRE_FUNCTIONS_INFO = new String[]{
        "CURRENT_DATABASE",
        "CURRENT_QUERY",
        "CURRENT_SCHEMA",
        "CURRENT_SCHEMAS",
        "INET_CLIENT_ADDR",
        "INET_CLIENT_PORT",
        "INET_SERVER_ADDR",
        "INET_SERVER_PORT",
        "ROW_SECURITY_ACTIVE",
        "FORMAT_TYPE",
        "TO_REGCLASS",
        "TO_REGPROC",
        "TO_REGPROCEDURE",
        "TO_REGOPER",
        "TO_REGOPERATOR",
        "TO_REGTYPE",
        "TO_REGNAMESPACE",
        "TO_REGROLE",
        "COL_DESCRIPTION",
        "OBJ_DESCRIPTION",
        "SHOBJ_DESCRIPTION",
        "TXID_CURRENT",
        "TXID_CURRENT_IF_ASSIGNED",
        "TXID_CURRENT_SNAPSHOT",
        "TXID_SNAPSHOT_XIP",
        "TXID_SNAPSHOT_XMAX",
        "TXID_SNAPSHOT_XMIN",
        "TXID_VISIBLE_IN_SNAPSHOT",
        "TXID_STATUS"
    };

    public static String[] POSTGRE_FUNCTIONS_COMPRASION = new String[]{
        "NUM_NONNULLS",
        "NUM_NULLS"
    };

    public static String[] POSTGRE_FUNCTIONS_FORMATTING = new String[]{
        "TO_CHAR",
        "TO_DATE",
        "TO_NUMBER",
        "TO_TIMESTAMP"
    };

    public static String[] POSTGRE_FUNCTIONS_ENUM = new String[]{
        "ENUM_FIRST",
        "ENUM_LAST",
        "ENUM_RANGE"
    };

    public static String[] POSTGRE_FUNCTIONS_SEQUENCE = new String[]{
        "CURRVAL",
        "LASTVAL",
        "NEXTVAL",
        "SETVAL"
    };

    public static String[] POSTGRE_FUNCTIONS_BINARY_STRING = new String[]{
        "GET_BIT",
        "GET_BYTE",
        "SET_BIT",
        "SET_BYTE"
    };

    public static String[] POSTGRE_FUNCTIONS_CONDITIONAL = new String[]{
        "COALESCE",
        "NULLIF",
        "GREATEST",
        "LEAST"
    };

    public static String[] POSTGRE_FUNCTIONS_TRIGGER = new String[]{
        "SUPPRESS_REDUNDANT_UPDATES_TRIGGER"
    };

    public static String[] POSTGRE_FUNCTIONS_SRF = new String[]{
        "GENERATE_SERIES",
        "GENERATE_SUBSCRIPTS"
    };

    public static String[] POSTGRE_KEYWORDS = new String[]{
        "SHOW",
        "TYPE",
        "USER",
        "COMMENT",
        "MATERIALIZED",
        "ILIKE",
        "ELSIF",
        "ELSEIF",
        "ANALYSE",
        "ANALYZE",
        "CONCURRENTLY",
        "FREEZE",
        "LANGUAGE",
        "MODULE",
        "OFFSET",
        //"PUBLIC",
        "RETURNING",
        "VARIADIC",
        "PERFORM",
        "FOREACH",
        "LOOP",
        "PERFORM",
        "RAISE",
        "NOTICE",
        "CONFLICT",
        "EXTENSION",

        // "DEBUG", "INFO", "NOTICE", "WARNING", // levels
        // "MESSAGE", "DETAIL", "HINT", "ERRCODE", //options

        "DATATYPE",
        "TABLESPACE",
        "REFRESH"
    };

    public static final String[] OTHER_TYPES_FUNCTION = {
        "CURRENT_DATE",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_ROLE",
        "CURRENT_USER",
    };



    public static String[] POSTGRE_FUNCTIONS_TEXT_SEARCH = new String[]{
        "ARRAY_TO_TSVECTOR",
        "GET_CURRENT_TS_CONFIG",
        "NUMNODE",
        "PLAINTO_TSQUERY",
        "PHRASETO_TSQUERY",
        "WEBSEARCH_TO_TSQUERY",
        "QUERYTREE",
        "SETWEIGHT",
        "STRIP",
        "TO_TSQUERY",
        "TO_TSVECTOR",
        "JSON_TO_TSVECTOR",
        "JSONB_TO_TSVECTOR",
        "TS_DELETE",
        "TS_FILTER",
        "TS_HEADLINE",
        "TS_RANK",
        "TS_RANK_CD",
        "TS_REWRITE",
        "TSQUERY_PHRASE",
        "TSVECTOR_TO_ARRAY",
        "TSVECTOR_UPDATE_TRIGGER",
        "TSVECTOR_UPDATE_TRIGGER_COLUMN"
    };


    public static String[] POSTGRE_FUNCTIONS_RANGE = new String[]{
        "ISEMPTY",
        "LOWER_INC",
        "UPPER_INC",
        "LOWER_INF",
        "UPPER_INF",
        "RANGE_MERGE"
    };


    public static String[] POSTGRE_FUNCTIONS_ADMIN = new String[]{
        "CURRENT_SETTING",
        "SET_CONFIG",
        "BRIN_SUMMARIZE_NEW_VALUES",
        "BRIN_SUMMARIZE_RANGE",
        "BRIN_DESUMMARIZE_RANGE",
        "GIN_CLEAN_PENDING_LIST"
    };


    public static String[] POSTGRE_FUNCTIONS_LO = new String[]{
        "LO_FROM_BYTEA",
        "LO_PUT",
        "LO_GET",
        "LO_CREAT",
        "LO_CREATE",
        "LO_UNLINK",
        "LO_IMPORT",
        "LO_EXPORT",
        "LOREAD",
        "LOWRITE",
        "GROUPING",
        "CAST"
    };


    public static String[] POSTGRE_FUNCTIONS_NETWROK = new String[]{
        "ABBREV",
        "BROADCAST",
        "HOST",
        "HOSTMASK",
        "MASKLEN",
        "NETMASK",
        "NETWORK",
        "SET_MASKLEN",
        "TEXT",
        "INET_SAME_FAMILY",
        "INET_MERGE",
        "MACADDR8_SET7BIT"
    };


    public static String[] POSTGRE_FUNCTIONS_GEOMETRY = new String[]{
        "AREA",
        "CENTER",
        "DIAMETER",
        "HEIGHT",
        "ISCLOSED",
        "ISOPEN",
        "NPOINTS",
        "PCLOSE",
        "POPEN",
        "RADIUS",
        "WIDTH",
        "BOX",
        "BOUND_BOX",
        "CIRCLE",
        "LINE",
        "LSEG",
        "PATH",
        "POLYGON"
    };


    public static String[] POSTGRE_FUNCTIONS_DATETIME = new String[]{
        "AGE",
        "CLOCK_TIMESTAMP",
        "DATE_PART",
        "DATE_TRUNC",
        "ISFINITE",
        "JUSTIFY_DAYS",
        "JUSTIFY_HOURS",
        "JUSTIFY_INTERVAL",
        "MAKE_DATE",
        "MAKE_INTERVAL",
        "MAKE_TIME",
        "MAKE_TIMESTAMP",
        "MAKE_TIMESTAMPTZ",
        "STATEMENT_TIMESTAMP",
        "TIMEOFDAY",
        "TRANSACTION_TIMESTAMP"
    };


    public static String[] POSTGRE_FUNCTIONS_MATH = new String[]{
        "ACOSD",
        "ASIND",
        "ATAN2D",
        "ATAND",
        "CBRT",
        "CEIL",
        "CEILING",
        "COSD",
        "COTD",
        "DIV",
        "EXP",
        "LN",
        "MOD",
        "RANDOM",
        "SCALE",
        "SETSEED",
        "SIND",
        "TAND",
        "TRUNC",
        "WIDTH_BUCKET"
    };


    public static String[] POSTGRE_FUNCTIONS_WINDOW = new String[]{
        "ROW_NUMBER",
        "RANK",
        "DENSE_RANK",
        "CUME_DIST",
        "NTILE",
        "LAG",
        "LEAD",
        "FIRST_VALUE",
        "LAST_VALUE",
        "NTH_VALUE"
    };


    public static final String[] POSTGIS_FUNCTIONS = {

        // 8.3. Management Functions

        "AddGeometryColumn",
        "DropGeometryColumn",
        "DropGeometryTable",
        "PostGIS_Full_Version",
        "PostGIS_GEOS_Version",
        "PostGIS_Liblwgeom_Version",
        "PostGIS_LibXML_Version",
        "PostGIS_Lib_Build_Date",
        "PostGIS_Lib_Version",
        "PostGIS_PROJ_Version",
        "PostGIS_Scripts_Build_Date",
        "PostGIS_Scripts_Installed",
        "PostGIS_Scripts_Released",
        "PostGIS_Version",
        "Populate_Geometry_Columns",
        "UpdateGeometrySRID",

        // 8.4. Geometry Constructors

        "ST_BdPolyFromText",
        "ST_BdMPolyFromText",
        "ST_Box2dFromGeoHash",
        "ST_GeogFromText",
        "ST_GeographyFromText",
        "ST_GeogFromWKB",
        "ST_GeomFromTWKB",
        "ST_GeomCollFromText",
        "ST_GeomFromEWKB",
        "ST_GeomFromEWKT",
        "ST_GeometryFromText",
        "ST_GeomFromGeoHash",
        "ST_GeomFromGML",
        "ST_GeomFromGeoJSON",
        "ST_GeomFromKML",
        "ST_GMLToSQL",
        "ST_GeomFromText",
        "ST_GeomFromWKB",
        "ST_LineFromEncodedPolyline",
        "ST_LineFromMultiPoint",
        "ST_LineFromText",
        "ST_LineFromWKB",
        "ST_LinestringFromWKB",
        "ST_MakeBox2D",
        "ST_3DMakeBox",
        "ST_MakeLine",
        "ST_MakeEnvelope",
        "ST_MakePolygon",
        "ST_MakePoint",
        "ST_MakePointM",
        "ST_MLineFromText",
        "ST_MPointFromText",
        "ST_MPolyFromText",
        "ST_Point",
        "ST_PointFromGeoHash",
        "ST_PointFromText",
        "ST_PointFromWKB",
        "ST_Polygon",
        "ST_PolygonFromText",
        "ST_WKBToSQL",
        "ST_WKTToSQL",

        //8.5. Geometry Accessors

        "GeometryType",
        "ST_Boundary",
        "ST_CoordDim",
        "ST_Dimension",
        "ST_EndPoint",
        "ST_Envelope",
        "ST_BoundingDiagonal",
        "ST_ExteriorRing",
        "ST_GeometryN",
        "ST_GeometryType",
        "ST_InteriorRingN",
        "ST_IsPolygonCCW",
        "ST_IsPolygonCW",
        "ST_IsClosed",
        "ST_IsCollection",
        "ST_IsEmpty",
        "ST_IsRing",
        "ST_IsSimple",
        "ST_IsValid",
        "ST_IsValidReason",
        "ST_IsValidDetail",
        "ST_M",
        "ST_NDims",
        "ST_NPoints",
        "ST_NRings",
        "ST_NumGeometries",
        "ST_NumInteriorRings",
        "ST_NumInteriorRing",
        "ST_NumPatches",
        "ST_NumPoints",
        "ST_PatchN",
        "ST_PointN",
        "ST_Points",
        "ST_SRID",
        "ST_StartPoint",
        "ST_Summary",
        "ST_X",
        "ST_XMax",
        "ST_XMin",
        "ST_Y",
        "ST_YMax",
        "ST_YMin",
        "ST_Z",
        "ST_ZMax",
        "ST_Zmflag",
        "ST_ZMin",

        //8.6. Geometry Editors

        "ST_AddPoint",
        "ST_Affine",
        "ST_Force2D",
        "ST_Force3D",
        "ST_Force3DZ",
        "ST_Force3DM",
        "ST_Force4D",
        "ST_ForcePolygonCCW",
        "ST_ForceCollection",
        "ST_ForcePolygonCW",
        "ST_ForceSFS",
        "ST_ForceRHR",
        "ST_ForceCurve",
        "ST_LineMerge",
        "ST_CollectionExtract",
        "ST_CollectionHomogenize",
        "ST_Multi",
        "ST_Normalize",
        "ST_RemovePoint",
        "ST_Reverse",
        "ST_Rotate",
        "ST_RotateX",
        "ST_RotateY",
        "ST_RotateZ",
        "ST_Scale",
        "ST_Segmentize",
        "ST_SetPoint",
        "ST_SetSRID",
        "ST_SnapToGrid",
        "ST_Snap",
        "ST_Transform",
        "ST_Translate",
        "ST_TransScale",

        //8.7. Geometry Outputs

        "ST_AsBinary",
        "ST_AsEncodedPolyline",
        "ST_AsEWKB",
        "ST_AsEWKT",
        "ST_AsGeoJSON",
        "ST_AsGML",
        "ST_AsHEXEWKB",
        "ST_AsKML",
        "ST_AsLatLonText",
        "ST_AsSVG",
        "ST_AsText",
        "ST_AsTWKB",
        "ST_AsX3D",
        "ST_GeoHash",
        "ST_AsGeobuf",
        "ST_AsMVTGeom",
        "ST_AsMVT",


    };

}
